Add product Poof Links
Politiwatch/privacyspy pull request #112
Opened 2021-08-14 06:41 UTC by sjoseph7

**Type of pull request:** product addition 

*Full Disclosure: I am the creator of Poof Links.*

2021-08-15 21:47 UTC, doamatto requested changes
Overall solid; a few tweaks I would make though

2021-08-15 21:47 UTC, doamatto commented on products/pooflinks.toml
> +[rubric.history]
Not required, but it’s nice to have the date provided here as a mini timestamp to see if it needs updating (while we wait on me to finish the scrubber)

2021-08-15 21:47 UTC, doamatto commented on products/pooflinks.toml
> +  "\"If you lose your URL, we cannot retrieve your secret for you.\""
Doesn't really pertain to data protection imo

2021-08-18 00:21 UTC, sjoseph7 commented on products/pooflinks.toml
> +  "\"If you lose your URL, we cannot retrieve your secret for you.\""
Do you have any recommendations for improving this section?

2021-08-18 16:08 UTC, milesmcc commented on products/pooflinks.toml
> +  "\"If you lose your URL, we cannot retrieve your secret for you.\""
In general I think it's good to avoid references to "military grade" encryption.

2021-08-19 06:16 UTC, sjoseph7 commented on products/pooflinks.toml
> +  "\"If you lose your URL, we cannot retrieve your secret for you.\""
I've modified the notes/citations and downgraded the rating.

2021-08-20 04:21 UTC, doamatto approved these changes
Looks good now; cheers

2021-08-20 04:30 UTC, merged