Add Grammarly
Politiwatch/privacyspy pull request #113
Opened 2021-08-18 05:26 UTC by ElijahPepe

**Type of pull request:** product addition

**Related issues:** #111

2021-08-18 16:04 UTC, milesmcc commented
Well done! Generally looks great to me. I suspect @doamatto will have some small feedback but in general, I think this is good to go (provided tests pass).

2021-08-20 04:31 UTC, doamatto requested changes
One thing to touch up; looks good outside of that though. @milesmcc feel free to tell the bot to auto-assign me PRs if you guys want.

2021-08-20 04:31 UTC, doamatto commented on products/grammarly.toml
> +  "When you interact with our Site, Software, and/or Services, we collect information that could be used to identify you (“Personal Data”). Some of the information we collect is stored in a manner th
Quote currently is contradicting. This can be remedied by including the mentions of how they use cookies for advertising Grammarly services/products

2021-08-20 04:31 UTC, doamatto commented on products/grammarly.toml
> +notes = [
It would be nice to have the data that is collected listed, but not required, ofc

2021-08-21 03:14 UTC, merged