Adding Tresorit.
Politiwatch/privacyspy pull request #126
Opened 2022-01-13 16:49 UTC by DimitriDR

**Type of pull request:** product addition

**Related issues:** N/A

---

Hey folks,
My first contribution here. I give you a new addition to the family of cloud storage.

2022-01-13 22:59 UTC, doamatto requested changes
Good start; needs some more work however before it can be merged.

2022-01-13 22:59 UTC, doamatto commented on products/tresorit.toml
> +    "[...] we may use your email address and phone number provided to us to send you marketing communications, [...], **unless you have opted-out**."
Should also mention use of web stats and logs

> We may also use information about you, including web statistics and logs, to personalize the content and experience you receive on our websites or in our marketing communications, as well as by displaying Tresorit ads on other companies' websites and applications, such as on platforms like Facebook and Google. Where legally required, also seek your consent for sending marketing communications.

2022-01-13 22:59 UTC, doamatto commented on products/tresorit.toml
> +notes = [
I don't see mention of this is the privacy policy. I do see it can be done by emailing them (`delete your personal data.`--`You can request this by send an email to support@tresorit.com.`)

2022-01-13 22:59 UTC, doamatto commented on products/tresorit.toml
> +    "At the bottom of the privacy policy, you can observe the archives."
Needs some rephrasing. Seems a bit wordy as is.

2022-01-13 22:59 UTC, doamatto commented on products/tresorit.toml
> +    "Tresorit may transmit personal data if the applicable legal provisions so require, or when such action is necessary to comply with any laws, including to meet national security or law enforcemen
More aptly `reasonable` as it's as necessary, but not `strict` as it isn't exclusively given in court order, subpoena, et al.

2022-01-13 22:59 UTC, doamatto commented on products/tresorit.toml
> +    "No mean."
No note needed.

2022-01-13 22:59 UTC, doamatto commented on products/tresorit.toml
> +value = "no"
Could argue Marketing, Aggregate Insights, and "Other purposes" are all non-critical uses.

2022-01-13 22:59 UTC, doamatto commented on products/tresorit.toml
> +    "ISO controls annually"
This comment doesn't add anything of importance and can be removed

2022-01-13 22:59 UTC, doamatto commented on products/tresorit.toml
> +    "We take appropriate technical and organizational measures to protect your personal data against loss or other forms of unlawful processing. Tresorit is ISO 27001:2013 certified."
Should note who audits and where to read more about the audits

2022-01-13 22:59 UTC, doamatto commented on products/tresorit.toml
> +    "In certain cases we need to share information, including personal data with our third-party service providers. We use third-party service providers for a number of services, including applicatio
There is a list of providers mentioned a few sentences later: https://support.tresorit.com/hc/en-us/articles/216114397-Third-party-services

2022-01-14 07:38 UTC, DimitriDR commented on products/tresorit.toml
> +notes = [
Actually, you can do it both ways: https://support.tresorit.com/hc/en-us/articles/360008033453-How-to-delete-your-account or by sending e-mail.

2022-01-14 16:04 UTC, doamatto commented on products/tresorit.toml
> +notes = [
In that case, I'd make a note to that page explaining that it can be used for self-service data deletion, but still also cite that you can request deletion over email.

2022-01-14 21:37 UTC, milesmcc commented
Thanks @doamatto for all the comments.

2022-01-16 20:54 UTC, doamatto requested changes

2022-01-16 20:54 UTC, doamatto commented on products/tresorit.toml
> +value = "no"
Could still be argued that marketing and "other purposes" are non-critical.

2022-01-16 20:54 UTC, doamatto commented on products/tresorit.toml
> +    "TÜV Rheinland Group has made the ISO certification."
A link to the audit or where to find the audit might not be a bad idea

2022-01-16 22:34 UTC, DimitriDR commented on products/tresorit.toml
> +value = "no"
I don't understand what do you mean. What do you want me to write?

2022-02-07 21:37 UTC, closed without merging