Update v0lt.toml
Politiwatch/privacyspy pull request #143
Opened 2022-10-21 16:03 UTC by connervieira

I've the developer of V0LT, and I've made several changes to the privacy policy and privacy information since PrivacySpy surveyed the website. I've made appropriate changes. The privacy policy can be verified here: [https://v0lttech.com/privacy.php](https://v0lttech.com/privacy.php)

2022-10-21 16:38 UTC, doamatto requested changes

2022-10-21 16:38 UTC, doamatto commented on products/v0lt.toml
> -contributors = [ "cvieira", "doamatto" ]
Past contributors should not be removed. You should append yourself to the list.

2022-10-21 18:19 UTC, connervieira commented on products/v0lt.toml
> -contributors = [ "cvieira", "doamatto" ]
I'm "cvieira", from when PrivacySpy used a different submission system. It stands for Conner Vieira. I thought I'd replace it to prevent conflicts. I'm happy to add it back for sake of completeness.

2022-10-23 23:23 UTC, milesmcc commented on products/v0lt.toml
> -contributors = [ "cvieira", "doamatto" ]
Changing your name is fine

2022-10-23 23:35 UTC, doamatto approved these changes

2022-10-24 04:55 UTC, merged