feat: Added "Wise" aka "TransferWise"
Politiwatch/privacyspy pull request #154
Opened 2023-02-28 07:19 UTC by ItsIgnacioPortal

**Type of pull request:** product addition

2023-02-28 14:31 UTC, doamatto requested changes
A few changes I think should be made (might be some compilation issues too to follow). Overall, great start!

2023-02-28 14:31 UTC, doamatto commented on CONTRIBUTORS.toml
> +email = "5990@protonmail.com"
It's really semantics, but there should be a blank line as the last line of a file instead of it just ending.

2023-02-28 14:31 UTC, doamatto commented on products/wise.toml
> +description = "Wise (formerly TransferWise) is a UK-based foreign exchange financial technology company founded by Estonian businessmen Kristo Käärmann and Taavet Hinrikus in January 2011."
There might be a way to make this a bit shorter. Although the other information is important to a degree, it isn't necessarily focal.

2023-02-28 14:31 UTC, doamatto commented on products/wise.toml
> +  "For example: \"We will use your personal data ... to prevent and detect crimes, including fraud and financial crime. Lawful basis for processing, including basis of legitimate interest: \"Legal ob
I can't seem to find this quote— perhaps it's just poorly formatted, but citations should be direct from the text with little to no modification (bar escaping quotes `\"` and what not).

2023-02-28 14:31 UTC, doamatto commented on products/wise.toml
> +  "11.2 We will always delete data that is no longer required by a relevant law or jurisdiction in which we operate. We do this automatically, so you don’t need to contact us to ask us to delete your
11.2 seems to be about data retention, not data deletion. This would be the equivalent of saying that Google provides an automated data deletion method because they offer ways for you to have data deleted automatically over time.

Sections 13 and 14 are likely more fruitful as the detail the rights for deletion. Two citations from these sections and how to exercise them would likely be more ideal.

2023-02-28 14:31 UTC, doamatto commented on products/wise.toml
> +  "The date the policy was last modified is listed. The previous policy is also listed for 60 days."
I would argue that this would be only `last-modified` (feel free to disagree)— the policy shows only the last version and only for a temporary amount of time. For something to get a full points, it needs to have a changelog, past versions, revisions, et al.; but after 60 days, the score would have to change to go back down to `last-modified`, which isn't practical to maintain.

cc @milesmcc

2023-02-28 14:31 UTC, doamatto commented on products/wise.toml
> +  "5.1 We may share your personal data with the following third parties:  advertisers and advertising networks to select and serve relevant adverts to you and others; analytics and search engine prov
It seems this isn't quite a direct quote and omits the first bullet point. It might be easier to do what you've done for a few others and make seperate items for each of the relevant bullet points

2023-02-28 15:20 UTC, milesmcc commented on products/wise.toml
> +  "The date the policy was last modified is listed. The previous policy is also listed for 60 days."
Agree. A bit weird that they only show history after 60 days. My expectation is that to get `yes`, they have to show the full history (or at least some non-trivial number of past revisions).

2023-03-01 01:33 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "11.2 We will always delete data that is no longer required by a relevant law or jurisdiction in which we operate. We do this automatically, so you don’t need to contact us to ask us to delete your
> This would be the equivalent of saying that Google provides an automated data deletion method because they offer ways for you to have data deleted automatically over time.

Is that not the point of the `rubric.data-deletion` question?

2023-03-01 01:38 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "https://wise.com/help/articles/2974131?origin=search-entities"
I disagree. That's not a link I found elsewhere. That's the link that the citation points to where it says:
> which can be found by clicking **here**

2023-03-01 02:03 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "We may share your personal data ... in response to a subpoena, warrant, court order, properly constituted police request or as otherwise required by law;"
Done

2023-03-01 02:03 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "5.1 We may share your personal data with the following third parties:  advertisers and advertising networks to select and serve relevant adverts to you and others; analytics and search engine prov
Done

2023-03-01 02:04 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "The date the policy was last modified is listed. The previous policy is also listed for 60 days."
Fair enough. Fixed.

2023-03-01 02:05 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "For example: \"We will use your personal data ... to prevent and detect crimes, including fraud and financial crime. Lawful basis for processing, including basis of legitimate interest: \"Legal ob
Done

2023-03-01 02:05 UTC, ItsIgnacioPortal commented on products/wise.toml
> +description = "Wise (formerly TransferWise) is a UK-based foreign exchange financial technology company founded by Estonian businessmen Kristo Käärmann and Taavet Hinrikus in January 2011."
Done

2023-03-01 02:05 UTC, ItsIgnacioPortal commented on CONTRIBUTORS.toml
> +email = "5990@protonmail.com"
Done

2023-03-01 02:12 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "2.3 Information we receive from other sources. We may receive information about you if you use any of the other websites we operate or the other services we provide. We also work closely with thir
Done

2023-03-01 03:03 UTC, doamatto commented on products/wise.toml
> +  "11.2 We will always delete data that is no longer required by a relevant law or jurisdiction in which we operate. We do this automatically, so you don’t need to contact us to ask us to delete your
Data deletion would be requesting your account is deleted (or deleting it yourself), in my opinion. The rubric could be more specific, but that's what I interpret as "permanently delet[ing] your personal data".

This would just be deleting a small subset of your data, not all of it.

2023-03-01 03:04 UTC, doamatto commented on products/wise.toml
> +  "https://wise.com/help/articles/2974131?origin=search-entities"
This I understand. Since there's no physically clickable point in citations (last I checked at least), it would be better to put this in the notes so that it can be clicked. It could also cause issues in the future with the scraper being worked on since that's not actually text on the page but the attribute value of a tag.

2023-03-03 03:36 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "https://wise.com/help/articles/2974131?origin=search-entities"
I've moved all links from the citations to the notes

2023-03-03 03:37 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "11.2 We will always delete data that is no longer required by a relevant law or jurisdiction in which we operate. We do this automatically, so you don’t need to contact us to ask us to delete your
I've added all mentions of data deletion to the citations

2023-04-18 14:14 UTC, doamatto requested changes
Seems I never sent this last one – sorry !

2023-04-22 16:47 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "2. Data we collect about you", "Personal data, or personal information, means any information about an identified or identifiable individual. It does not include anonymous data, which cannot be li
Looks like the github toml syntax higthlighter doesn't deal well with long lines. I checked manually, and there's no syntax-breaking double-quotes in the entire citation. It might be worth it to [report this to github](https://support.github.com/contact/bug-report)

2023-04-22 17:09 UTC, ItsIgnacioPortal commented on products/wise.toml
> +  "2. Data we collect about you", "Personal data, or personal information, means any information about an identified or identifiable individual. It does not include anonymous data, which cannot be li
[I've verified that this is an issue with github](https://github.com/ItsIgnacioPortal/testrepo/blob/main/biglines.toml) and I've reported it

2023-06-06 01:25 UTC, doamatto approved these changes
Sorry for the wait ! Looks all good to me.

2023-06-06 01:25 UTC, merged