Product addition: 1.1.1.1
Politiwatch/privacyspy pull request #155
Opened 2023-03-01 11:20 UTC by adamlui

**Type of pull request:** product addition

**Related issues:** no issues

2023-03-02 15:47 UTC, doamatto requested changes
Good start! Re-request a review when you're ready for me to take another look.

2023-03-02 15:47 UTC, doamatto commented on products/1-1-1-1.toml
> +value = "no"
Is it possible that this would be `na` instead? My impression was that there were no accounts or any data that could be (within reason) traced back to an individual person.

2023-03-02 15:47 UTC, doamatto commented on products/1-1-1-1.toml
> +  "\"We only collect and store the minimum amount of data we believe is required to operate and improve the Application. There are three categories of data that we collect: Account Data, Operational
Although `na` is likely the best value, this citation doesn't really help. A note saying that they don't collect contact information to be able to disclose breaches might be a better solution (see [Quad9](https://privacyspy.org/product/quad9/)).

2023-03-02 15:47 UTC, doamatto commented on products/1-1-1-1.toml
> +notes = [
This note *might* be unnecessary. Although it may not be common knowledge, it is readily available knowledge that not everyone is informed that they're being investigated.

cc @milesmcc

2023-03-02 15:47 UTC, doamatto commented on products/1-1-1-1.toml
> +  "\"[W]e may also share your information with others [...] [w]hen we are required to disclose personal information to respond to subpoenas, court orders, or legal process[.]\n\n[. ..]\n\nOur commitm
`always` might not be the right score given this citation. `reasonable` seems, no pun intended, more reasonable— some kind of process is required as opposed to constantly feeding the data out.

2023-03-02 15:47 UTC, doamatto commented on products/1-1-1-1.toml
> +  "\"We do not sell, rent, or share personal information with third parties as defined under the California Consumer Privacy Act of 2018 (California Civil Code Sec. 1798.100 et seq.), nor do we sell,
Wouldn't sending data to APNIC constitute as third-party access/sharing? A value like `yes-specified-noncritical` would likely be more fitting.

2023-03-02 16:39 UTC, adamlui commented on products/1-1-1-1.toml
> +value = "no"
Your guideline for NA states " The service doesn't collect any personal information." If you changed it to "collects so little personal data " (which `data-breaches`'s NA states) then the little they do (email, IP address) would qualify it

2023-03-02 16:41 UTC, adamlui commented on products/1-1-1-1.toml
> +  "\"We only collect and store the minimum amount of data we believe is required to operate and improve the Application. There are three categories of data that we collect: Account Data, Operational
The citation indeed helps reader understand why N/A by your criterion ("collects so little personal data") is true. You can change it to a note if you want I don't care (I assumed you wanted citations to inform beyond notes)

2023-03-02 16:42 UTC, adamlui commented on products/1-1-1-1.toml
> +notes = [
I certainly did not know this (and I've been thru the legal system)

2023-03-02 16:49 UTC, adamlui commented on products/1-1-1-1.toml
> +  "\"[W]e may also share your information with others [...] [w]hen we are required to disclose personal information to respond to subpoenas, court orders, or legal process[.]\n\n[. ..]\n\nOur commitm
I simply used https://privacyspy.org/product/any-do/ as a guide ("always" for policy admitting compliance w/ law + in response to requests, same as 1.1.1.1's) to correctly conclude that Cloudflare will always allow such access. What process do you refer to that somehow makes this less true?

2023-03-02 16:49 UTC, adamlui commented on products/1-1-1-1.toml
> +  "\"[W]e may also share your information with others [...] [w]hen we are required to disclose personal information to respond to subpoenas, court orders, or legal process[.]\n\n[. ..]\n\nOur commitm
(the question is do they allow access not how)

2023-03-02 16:50 UTC, adamlui commented on products/1-1-1-1.toml
> +  "\"We do not sell, rent, or share personal information with third parties as defined under the California Consumer Privacy Act of 2018 (California Civil Code Sec. 1798.100 et seq.), nor do we sell,
The citation states "anonymized data"

2023-03-02 16:52 UTC, adamlui commented
> Good start! Re-request a review when you're ready for me to take another look.

I don't know what this means

2023-03-02 17:05 UTC, adamlui commented on products/1-1-1-1.toml
> +notes = [
I told clients when police requested their SSN when I worked at a homeless shelter. The purpose of notes should be to inform readers which companies *don't* operate that way, without driving traffic away by suggesting they research "readily available knowledge" which would make every note irrelevant by your logic (are privacy policies not readily available?)

2023-03-02 20:37 UTC, adamlui commented
I no longer want to contribute to this project

2023-03-02 20:37 UTC, closed without merging

2023-03-02 23:40 UTC, doamatto commented on products/1-1-1-1.toml
> +  "\"[W]e may also share your information with others [...] [w]hen we are required to disclose personal information to respond to subpoenas, court orders, or legal process[.]\n\n[. ..]\n\nOur commitm
`always` wouldn't be in compliance with law, per se. It would be that there is a firehose of data available for the government to use rather than using the proper legal process for obtaining data. If `always` was described as if a service ever could share data, basically anything on the internet could fit that criteria in my eyes.

2023-03-02 23:50 UTC, milesmcc commented
😕

2023-03-03 04:12 UTC, adamlui commented on products/1-1-1-1.toml
> +  "\"[W]e may also share your information with others [...] [w]hen we are required to disclose personal information to respond to subpoenas, court orders, or legal process[.]\n\n[. ..]\n\nOur commitm
> always wouldn't be in compliance with law, per se. It would be that there is a firehose of data available for the government to use rather than using the proper legal process for obtaining data

Read the actual question: "When does the policy allow law enforcement access to personal data?"

What part of that does answering "always" have anything to do with firehoses? The answer to this question literally means "The policy always allows law enforcement access." It has literally nothing to do with what you say...

> If always was described as if a service ever could share data...

Not "could" the question literally asks "does" (and no need for if's necessary, just read the question it literally asks that)

> ...basically anything on the internet could fit that criteria in my eyes.

No, not basically every company in the world always allows access lol you must be joking

2023-03-03 04:21 UTC, adamlui commented
> 😕

How do you remove this from my profile? (I never made pull requests on GitHub before)

2023-03-03 04:30 UTC, adamlui commented on products/1-1-1-1.toml
> +  "\"[W]e may also share your information with others [...] [w]hen we are required to disclose personal information to respond to subpoenas, court orders, or legal process[.]\n\n[. ..]\n\nOur commitm
And even if your false assumption were true, why would most things being a certain way to you bizarrely compel you to censor edge cases on a site who's entire existence is literally provide transparency...

2023-03-03 04:51 UTC, adamlui commented on products/1-1-1-1.toml
> +  "\"[W]e may also share your information with others [...] [w]hen we are required to disclose personal information to respond to subpoenas, court orders, or legal process[.]\n\n[. ..]\n\nOur commitm
And if firehoses exist, the question "When does the policy allow *anyone* access?" properly adresses it, not one concerning law enforcement (which the reader is expecting an answer on law enforcement requests obviously)

2023-03-03 05:25 UTC, adamlui commented on products/1-1-1-1.toml
> +  "\"[W]e may also share your information with others [...] [w]hen we are required to disclose personal information to respond to subpoenas, court orders, or legal process[.]\n\n[. ..]\n\nOur commitm
And I just noticed any.do was submitted by you lol. Your citation similarly cites processes that by your logic, should not be `always` yet you only criticize submissions of strangers that followed the same common sense. Why do you preach one thing but practice the opposite ?