added Stripe
Politiwatch/privacyspy pull request #156
Opened 2023-04-09 15:50 UTC by Deivedux

**Type of pull request:** product addition

**Related issues:** Only during the opening of this pull request did I notice that `behavioral-marketing` may be conflicting with `third-party-collection` in some way. Please let me know of any issues you may have with this version.

---

I decided not to add their security policy as a source, since the only one they have is for their API and not for the personal data processing, which, I think, is irrelevant here.

2023-04-09 20:43 UTC, Deivedux commented on products/stripe.toml
> +value = "no"
I have thoughts whether this should be `somewhat`, considering there's at least a mention of implied data security.

2023-04-15 15:25 UTC, doamatto requested changes
Solid start. Here's a few things I would change. Re-request the review when you think it's good for another look over.

2023-04-15 15:25 UTC, doamatto commented on products/stripe.toml
> +citations = [ "We may use your Personal Data to assess your eligibility for, and offer you, other End User Services or promote existing End User Services. Where allowed by law (including with your op
It may make sense to include 1.2.b§ "Advertising by Business Users" and similar sections for 1.3.b§ "Advertising" and 1.4.b§ "Advertising"

2023-04-15 15:25 UTC, doamatto commented on products/stripe.toml
> +  "The entirety of section 2 is a continuation, more exhaustive list of reasons how they use and share personal data."
This is not exclusive to 1.1.b, but also: 1.2.b, 1.3.b, & 1.4.b.

2023-04-15 15:25 UTC, doamatto commented on products/stripe.toml
> +value = "no"
The data they keep seems to be things required by law in the first place (Stripe isn't going to dodge taxes because you deleted your account).

4.b outlines data protection rights and links to their [Privacy Centre](https://stripe.com/en-gb/legal/privacy-center#exercise-rights) and [a "I would like to delete my account" KB page](https://support.stripe.com/questions/i-would-like-to-delete-the-information-stripe-has-collected-from-me). Both could be used to revise this section to be more accurate.

2023-04-15 15:25 UTC, doamatto commented on products/stripe.toml
> +notes = [ "The policy does not mention the collection of non-critical personal data." ]
An argument could be made that some non-critical collection and usage is done, namely: 
  - 1.1.b § Advertising
  - 1.2.b § Advertising by Business Users
  - 1.3.b § Advertising
  - 1.4.b § Personalization
  - 1.4.b § Advertising
  - 1.4.b § Engagement
  - 2.a § Online Activity
  - 2.b § Improving and Developing our Services (analytics and Cookie Policy)

2023-04-15 15:25 UTC, doamatto commented on products/stripe.toml
> +value = "no"
They make the same "reasonable" effort as any other company. You can add notes about their PCI certification or [their Security page](https://stripe.com/docs/security), but I wouldn't use it in the score since it doesn't add too much anyways

2023-04-15 15:25 UTC, doamatto commented on products/stripe.toml
> +notes = [ "The policy lists sharing of only critical data with third-parties, but does not explicitly list any of them." ]
A list of who they share data with [is available here](https://stripe.com/en-gb/legal/service-providers). Some non-critical providers are :
  - Marketo, Inc.
  - Google LLC (solely for "and to measure interactions on our Sites")

There may be more there – I just did a quick glance of their providers.

2023-07-11 18:34 UTC, Deivedux commented on products/stripe.toml
> +value = "no"
This is a difficult one, as it can be argued multiple ways, depending on what kind of user you are and what data you want to be deleted.

Closing an account is simple, and is an automated process. But if you're an End User of their Business Users, then some data can be deleted through automation, but others only by contacting them, such as Stripe Identity.

When I was originally editing this product, I thought of putting `na` as it seemed to me that they barely collect non-critical personal data, if any, anyway, and that the only data they do collect are ones that they are legally obligated to retain, anyway. Obviously, I'ved looked past that and ditched that idea after learning that Stripe does provide a way to delete personally identifiable information. Question now is, given that both options are present, I'm not sure which one is fair to pick here. I'd argue that it's basically automatic, and give them the benefit of the doubt that the data that requires contact to be deleted *should* actually have this strict identity verification, considering the type of data to be deleted in question.

Let me know of your thoughts on this.

2023-07-23 00:45 UTC, doamatto commented on products/stripe.toml
> +value = "no"
This privacy policy is written for both end-users and business users, which is admittedly a faux pas on Stripe's part since it makes it a bit vague. I think it would make sense to have it be `yes-contact` – end-users can't use an automated process to delete their data and must use the methods mentioned in their Privacy Centre. Saying `yes-automated` when it isn't true for both end-users and customers (as in businesses and the like) wouldn't make sense to me.

2023-07-23 00:49 UTC, doamatto requested changes
One more quick thing with the other comment. Sorry about the wait for me to get to this.

2023-07-23 00:49 UTC, doamatto commented on products/stripe.toml
> +notes = [ "The policy does not mention of an opt-out option from collection or use of any data for personalized marketing." ]
It seems it has a "right to opt-out of sharing of cross-context behavioral advertising" which could fit in your comment. 

They link to [here](https://stripe.com/fr-us/legal/privacy-center#what-data-may-be-shared-or-made-available-to-enable-me-to-see-stripe-ads-on-other-sites) and their cookie settings page.

2023-07-26 10:32 UTC, Deivedux commented on products/stripe.toml
> +value = "no"
Alright, so I'm assuming I'm putting this as `yes-contact` mainly because there's at least 1 piece of personal data that requires this method over automation. Makes sense to me.

2023-07-26 11:14 UTC, Deivedux commented on products/stripe.toml
> +notes = [ "The policy does not mention of an opt-out option from collection or use of any data for personalized marketing." ]
Unless this somehow implies that it affects everyone, I don't think it makes sense to be added as a comment, since this citation is only found under `8. Jurisdiction-specific provisions` for California citizens.

Though, their cookie settings page does seem to give them the benefit of allowing users to opt-out of analytical data.

2023-07-26 15:08 UTC, doamatto commented on products/stripe.toml
> +notes = [ "The policy does not mention of an opt-out option from collection or use of any data for personalized marketing." ]
Sure enough ! That said, the support for GPC for opting out of targeted advertising is enough to count as an opt-out alongside the cookies, in my opinion.

2023-07-27 11:54 UTC, Deivedux commented on products/stripe.toml
> +notes = [ "The policy does not mention of an opt-out option from collection or use of any data for personalized marketing." ]
Though, here's the thing. I'm uncertain if it's an opt-in or opt-out feature. Cookies are the kind of thing that all sites, including Stripe, ask whether to accept or reject all optional ones for first time visitors. Or does that only apply to EU users?

2023-07-27 14:01 UTC, doamatto commented on products/stripe.toml
> +notes = [ "The policy does not mention of an opt-out option from collection or use of any data for personalized marketing." ]
**TL;DR–** cookie opt-outs are a choice for everyone on Stripe's website and GPC makes the process faster and is legally recognised by both GDPR and CCPA, but anyone can use that setting too.

My understanding is that cookie requirements (in relation to GDPR and its soon-to-be-done-sibling nFADP, the Swiss version) apply to all EU citizens and residents. Similarly, the CCPA applies to all California residents. And whatever Nevada's law was called applies to all Nevadian (?) residents.

Most sites just throw up the cookie pop-up irrespective of location – it's easier to not geo-target. Going to the US version of Stripe's site doesn't prompt me to set my cookie preference, but I can still change them on the cookie settings page (and hope that it does *something*).

---

That all said, if you were referring to GPC, it's a browser signal (think good ol' `DNT`) that tells the site to not sell or share your data and is acknowledged as a fair and legitimate way to exercise rights under the CCPA and GDPR :

> The GPC signal will be intended to communicate a Do Not Sell request from a global privacy control, as per [CCPA-REGULATIONS §999.315](https://www.oag.ca.gov/sites/all/files/agweb/pdfs/privacy/oal-sub-final-text-of-regs.pdf) for that browser or device, or, if known, the consumer. Under the GDPR, the intent of the GPC signal is to convey a general request that data controllers limit the sale or sharing of the user’s personal data to other data controllers ([GDPR Articles 7 & 21](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016R0679)). Over time, the GPC signal may be intended to communicate rights in other jurisdictions.

source: [https://globalprivacycontrol.org/#gpc-spec](https://globalprivacycontrol.org/#gpc-spec)

2023-07-27 17:07 UTC, Deivedux commented on products/stripe.toml
> +notes = [ "The policy does not mention of an opt-out option from collection or use of any data for personalized marketing." ]
Since they don't prompt the cookie preference options for US citizens, I guess what we can do here is to see what the default cookie values are set for new visitors. If they're disabled by default, then we can do `opt-in`, otherwise it's `opt-out-*` depending on how many of them are pre-enabled.

Could you share what those default values are? I don't have access to such proxies to test it out myself at the moment.

2023-07-28 10:23 UTC, Deivedux commented on products/stripe.toml
> +notes = [ "The policy does not mention of an opt-out option from collection or use of any data for personalized marketing." ]
Alright, I just checked. They are all enabled by default, which makes sense when they don't have to ask for consent. So, I think it makes the most sense here to go with `opt-out-all`, since that's what they clearly want to do when they're not being limited by something like GDPR.

2023-07-29 18:33 UTC, doamatto commented on products/stripe.toml
> +notes = [ "The policy does not mention of an opt-out option from collection or use of any data for personalized marketing." ]
When I use Mullvad to reach an IP in Los Angeles, there isn't a pop-up, but going to the cookies page all of them are enabled. When I use my residential IP in France, there's a pop-up in the bottom right to manage cookies, accept all, or reject all – all cookie settings are set to the office position.

2023-08-06 16:53 UTC, doamatto approved these changes
Get this fixed real quick, and I'll merge it today.

2023-08-06 16:53 UTC, doamatto commented on products/stripe.toml
> +citations = [ "Last updated: January 24, 2023" ]
Bump this to the latest : `Last updated: May 17, 2023`

2023-08-09 05:00 UTC, merged