feat(products): Added Sans Institute (sansorg)
Politiwatch/privacyspy pull request #157
Opened 2023-04-18 06:18 UTC by ItsIgnacioPortal

**Type of pull request:** product addition

---

The product slug is `sansorg` instead of `sans` because I saw that sans.edu has it's own privacy policy, so using this unique slug should avoid a possible conflict in the future:

> When we refer to “Websites” we mean [www.sans.org](https://www.sans.org/) as well as the other websites that we operate and that link to this Policy. Note that GIAC has its own privacy policy at [www.giac/privacy](https://www.giac/privacy), and SANS Technical Institute has its own Privacy Policy at [www.sans.edu/privacy](https://www.sans.edu/privacy). This Policy does not apply to personal information collected and processed by GIAC or the SANS Technical Institute.

2023-04-18 14:12 UTC, doamatto requested changes
Great start. A few changes and it should be good to go.

2023-04-18 14:12 UTC, doamatto commented on products/sansorg.toml
> +  "Despite the SANS Institute being a beacon in the cybersecurity industry, whose sole focus is on cybersecurity, their privacy policy does not specify a data breach protocol. It also notes the follo
The language here is a bit passive agressive – the note afterwords would be better for `rubric.security`, if at all.

2023-04-18 14:12 UTC, doamatto commented on products/sansorg.toml
> +[rubric.data-collection-reasoning]
I would say that `no` isn't giving this a fair shake. The "How We Use Personal Information" outlines a fair amount of usage and doesn't seem to be \*too\* broad. Revise this criteria based on that section.

2023-04-18 14:12 UTC, doamatto commented on products/sansorg.toml
> +  "Disclosure of Personal Information",
Maybe include the paragraph above it as well ("Protect our rights ... comply with legal process (e.g., subpoenas or warrants)")

2023-04-18 14:12 UTC, doamatto commented on products/sansorg.toml
> +citations = [
It may be good to note the "Disclosure of Personal Information" section as well since it provides (still vague) but a marginally better picture of what is shared and for why.

2023-04-22 17:28 UTC, ItsIgnacioPortal commented on products/sansorg.toml
> +[rubric.data-collection-reasoning]
I feel like the justifications in that section aren't enough, considering the amount of information that they ask for during signup. Look at this screenshot, and note the field marked obligatory with a `*`:
![Screenshot 2023-04-22 at 14-23-00 SANS Institute](https://user-images.githubusercontent.com/46269721/233798124-f716a155-919a-48a0-96f2-52dde035f5d2.png)

Do you think a `somewhat` rating would be more fair?

2023-04-22 19:49 UTC, ItsIgnacioPortal commented on products/sansorg.toml
> +  "Disclosure of Personal Information",
Done

2023-04-22 19:58 UTC, ItsIgnacioPortal commented on products/sansorg.toml
> +citations = [
Yeah, that makes sense. Done

2023-04-22 20:04 UTC, ItsIgnacioPortal commented on products/sansorg.toml
> +  "Despite the SANS Institute being a beacon in the cybersecurity industry, whose sole focus is on cybersecurity, their privacy policy does not specify a data breach protocol. It also notes the follo
I've shortened that note now. I feel like it's important that we mention this, as it may otherwise come as a surprise for most users of SANS. Do you have any suggestions for a more professional phrasing?

2023-06-06 01:26 UTC, doamatto commented on products/sansorg.toml
> +[rubric.data-collection-reasoning]
Sorry for the delay. Just for sake of quickness – are you saying that the required fields are things that neither the service, nor logic, would require for the service ? I'm not familiar with Sans Institute, so I'm doing my general best to help :)

2023-06-06 01:30 UTC, ItsIgnacioPortal commented on products/sansorg.toml
> +[rubric.data-collection-reasoning]
Yes. For example, if you want to download free content from the SANS website, you need an account. Imagine giving away all of this information just to download a png

2023-06-06 01:42 UTC, doamatto commented on products/sansorg.toml
> +[rubric.data-collection-reasoning]
I agree that it's a bit excessive and know of plenty of services (like Pinterest) that require information for downloading from the service, likely with the logic of preventing excessive traffic or something of that sort.

That being said, the rubric criteria is defined as « Is it clear why the service collects the personal data that it does ? » and not « Is the data the service collects necessary and plausibly reasonable for it to its job ? » (that said, a criteria like that is something I wouldn't frown upon).

2023-06-06 01:51 UTC, ItsIgnacioPortal commented on products/sansorg.toml
> +[rubric.data-collection-reasoning]
It is not clear why such data is requested. It would make sense if this were the signup to become a teacher at SANS, but that is not the case.

2023-06-06 02:31 UTC, doamatto commented on products/sansorg.toml
> +[rubric.data-collection-reasoning]
Looking into the services offered by SANS Institute, it seems they training and provide certificates, and cite such as part of the reason why data is collected : 

> We also process and store data associated with training assignments, including scores on assessments you undertake

It is not an exclusive reason, as there are other reasons outlined in the "How We Use Personal Information" section. To say that there is no justification would be not true.

2023-06-06 05:29 UTC, ItsIgnacioPortal commented on products/sansorg.toml
> +[rubric.data-collection-reasoning]
That's fair. I've added the relevant citations from the "How We Use Personal Information" section, and a note. What do you think?

2023-06-06 13:57 UTC, doamatto commented on products/sansorg.toml
> +[rubric.data-collection-reasoning]
Looks good. I'll do one more look over and then go from there.

2023-06-13 04:08 UTC, ItsIgnacioPortal commented on products/sansorg.toml
> +  "In some cases the required information for signing up may be excesive. For example, an account is required to download resources related to \"CIS Controls v8\", yet in such cases it does not make
Fixed.

2023-06-15 15:33 UTC, doamatto approved these changes

2023-06-15 15:33 UTC, merged