feat(product): Added Kagi
Politiwatch/privacyspy pull request #174
Opened 2023-08-26 10:15 UTC by vkeerthivikram

**Type of pull request:** product addition 
---

Provide more information about your pull request here. For help, see our contribution guide: http://privacyspy.org/contribute/

Added Kagi Product

2023-09-23 18:31 UTC, doamatto requested changes
A lot of the quotes seem to be missing. I imagine that's likely in part for me taking a hot minute to get to this (which I apologise for), but if you can update this so that the quotes are matching what is on the privacy policy, I'd appreciate it a lot.

2023-09-23 18:31 UTC, doamatto commented on products/kagi.toml
> +  "Kagi only stores the limited information that a user explicitly provides through their account, such as email, account settings, and nothing else.",
Seems the line here is actually : 

> Kagi only stores the information about the client that you explicitly provide by using your account, as laid out in our interface.

2023-09-23 18:31 UTC, doamatto commented on products/kagi.toml
> +  "When a user searches on Kagi, their web browser sends the request to Kagi servers but Kagi transmits no information about the user to other third party services it queries to fulfill the search.",
Seems this line is missing from the policy. I won't duplicate this comment for other occurances, but do another read through and make sure your quotes are what are on the latest version of the policy.

2023-09-23 18:31 UTC, doamatto commented on products/kagi.toml
> +value = "strict"
This citation doesn't do anything to say that they have a strict policy. They're only being more transparent by stating what they have (or more aptly, haven't) received.

2023-09-26 10:22 UTC, vkeerthivikram commented
Hi  @doamatto I have done the required changes. Please let me know if I missed anything. Thank you!!

2023-10-27 17:29 UTC, doamatto requested changes
Sorry for the long wait again ; been very busy lately. These should be the last things needing a look-over. Thanks for all the work so far（＾_＾）

2023-10-27 17:29 UTC, doamatto commented on products/kagi.toml
> +  "IP addresses and uploaded content are only used as needed to fulfill specific user requests, such as location-based searches or reverse image lookups.",
Can't seem to find this in the policy (L35-36 only).

2023-10-27 17:29 UTC, doamatto commented on products/kagi.toml
> +"There is an option to delete your account."," When you do this, all information and settings related to your account is removed from our database."
Maybe @milesmcc has an opinion here, but I'm not sure the best score for this. I assume that the option to delete is in some settings pane (I don't use Kagi so I wouldn't know), but it's not verbatim here which makes me want to demote it to `yes-contact`. That said, it doesn't mention if deletion is done via contact either, with the only contact being the e-mail and Discord server used in the terms of service on the same page. Not sure the best course of action here ; just don't feel like keeping it is *fair* per se (we've demoted other scores because it's not verbatim in the past).

2023-10-27 17:29 UTC, doamatto commented on products/kagi.toml
> +citations = [
Clean-up all the newlines here that don't need to be, please.

2023-10-27 17:29 UTC, doamatto commented on products/kagi.toml
> +notes = [ "No data is used for non critical purposes.","There are some limited options for users to control caching, local storage, and account deletion, but do not explicitly mention opting out of n
A mention about the usage of Sentry may be a good idea.

2023-10-28 03:57 UTC, vkeerthivikram commented on products/kagi.toml
> +  "IP addresses and uploaded content are only used as needed to fulfill specific user requests, such as location-based searches or reverse image lookups.",
Seems Like I forgot to remove L35-L36 Will remove it.

2023-10-28 03:58 UTC, vkeerthivikram commented on products/kagi.toml
> +"There is an option to delete your account."," When you do this, all information and settings related to your account is removed from our database."
No Issue will change it to yes-contact

2023-10-28 03:59 UTC, vkeerthivikram commented on products/kagi.toml
> +citations = [
done

2023-10-28 04:00 UTC, vkeerthivikram commented on products/kagi.toml
> +notes = [ "No data is used for non critical purposes.","There are some limited options for users to control caching, local storage, and account deletion, but do not explicitly mention opting out of n
Mentioned both Sentry and GCP logging

2023-10-28 08:04 UTC, doamatto requested changes
I loosely commented on it one-last time™, but it seems to just be a bit of whitespace issues and formatting issues. Once those get fixed, I'll merge it.

2023-10-28 08:04 UTC, doamatto commented on products/kagi.toml
> +citations = ["All Kagi communications - inbound and outbound - are made over encrypted HTTPS.","HTTPS does not protect these other parties from knowing where the request is going, but it does protect
Citation should be on new line (after `[`)

2023-10-28 08:04 UTC, doamatto commented on products/kagi.toml
> +"To ensure your privacy and security, we don’t monitor, log or store your queries or associate them with your account. " ]
Closing bracket should be on new line

2023-10-28 08:04 UTC, doamatto commented on products/kagi.toml
> +
Fix whitespace, please

2023-10-28 08:04 UTC, doamatto commented on products/kagi.toml
> +"Kagi only stores the information about the client that you explicitly provide by using your account, as laid out in our interface."," This includes",
Should be one quote if succinct.

2023-10-28 16:29 UTC, vkeerthivikram commented on products/kagi.toml
> +"Kagi only stores the information about the client that you explicitly provide by using your account, as laid out in our interface."," This includes",
Sorry, first time I am working with TOML 😅.  Will keep all of this in mind when I add a new product. Have made the requested changes, and made stuff into one quote wherever possible, and removed white spaces and put all citation on a new line after `[`

2023-10-28 16:31 UTC, doamatto approved these changes

2023-10-28 16:31 UTC, merged