Add SMSPool
Politiwatch/privacyspy pull request #184
Opened 2024-06-05 17:54 UTC by smspool

**Type of pull request:** product addition
**Related issues:** list the related issues here (if applicable)

---

Privacy policy: https://www.smspool.net/privacy-policy
Terms of service: https://www.smspool.net/tos

Provide more information about your pull request here. For help, see our contribution guide: http://privacyspy.org/contribute/

2024-06-05 18:57 UTC, doamatto requested changes
Overall a good start. I'll approve checks and look it over once some changes are made.

2024-06-05 18:57 UTC, doamatto commented on products/smspool.toml
> +description = "Protect your identity today with our one-time use or rental phone numbers."
This makes it seem like Politiwatch/PrivacySpy is endorsing SMSPool or that it's a product internally. Can we get this reworded so that it's just a description for the product itself ? Take a look at other products or let me know if you need examples of such.

2024-06-05 18:57 UTC, doamatto commented on products/smspool.toml
> +  "SMSPool does not store or require any personal data"
Quoting and scoring based on Article 6 would be ideal. Data is still stored and collected nevertheless.

2024-06-05 18:57 UTC, doamatto commented on products/smspool.toml
> +value = "last-modified"
If I recall correctly, this will fail tests when I approve them to run. Just add a quote that shows the "Most recent updated" line and it should be fine.

2024-06-05 18:57 UTC, doamatto commented on products/smspool.toml
> +value = "yes-automated"
This doesn't explicitly tell us that it's an automated process like using a delete button in a settings menu. Either the policy needs to be remedied or it should be scored as `yes-contact`.

2024-06-05 18:57 UTC, doamatto commented on products/smspool.toml
> +value = "no"
Access is shared with Cloudflare (critical based on "CDN and DDoS protection") and Stripe (critical because payments). If that's all the parties (unsure myself), the `yes-specified-critical` value would be ideal.

2024-06-05 18:57 UTC, doamatto commented on products/smspool.toml
> +[rubric.noncritical-purposes]
Will fail test. Needs a citation or note. I know @milesmcc was talking with me a while back about how some analytics might be deemed critical. I'll touch base with him off GH and see if he wants to move the line for analytics or not. Assume for the time being that won't be the case, which means analytics is non-critical.

2024-06-05 18:57 UTC, doamatto commented on products/smspool.toml
> +value = "reasonable"
This should be `unspecified` with a citation on the tracking for fradulent behaviour. There's no mention of when data would be shared with law enforcement.

2024-06-05 18:57 UTC, doamatto commented on products/smspool.toml
> +value = "na"
Should be `summarily`. Missing note or citation.

2024-06-05 18:57 UTC, doamatto commented on products/smspool.toml
> +value = "na"
This is a tough one that I'll also bring up to @milesmcc — you can for some users but not all. I think `na` works here, but I'll run it by him regardless just to get another pair of eyes on it. Also please add a blank line to the bottom of your file

2024-06-05 19:05 UTC, smspool commented
Cheers for the input, I will work on it now.

2024-06-26 16:57 UTC, doamatto commented on products/smspool.toml
> +description = "Protect your identity today with our one-time use or rental phone numbers."
Fixed in 2855b7271cc0534780a0c5fbdce51003640134d3.

2024-06-26 16:59 UTC, doamatto commented on products/smspool.toml
> +value = "yes-automated"
Fixed in 2855b7271cc0534780a0c5fbdce51003640134d3.

2024-06-26 16:59 UTC, doamatto commented on products/smspool.toml
> +value = "no"
Fixed in 2855b7271cc0534780a0c5fbdce51003640134d3.

2024-06-26 17:03 UTC, doamatto commented on products/smspool.toml
> +[rubric.noncritical-purposes]
The verdict here was that analytics will continue to be marked as non-critical. Since Cloudflare's analytics are mentioned in Article 2, this should be marked as `no` ; unless you mean the site statistics from having stuff under clouds and not their proper analyitcs offering, then it would stay as `na`. No policy change would be needed, just clarification here.

2024-06-26 17:03 UTC, doamatto commented on products/smspool.toml
> +value = "reasonable"
Fixed in 2855b7271cc0534780a0c5fbdce51003640134d3.

2024-06-26 17:04 UTC, doamatto commented on products/smspool.toml
> +value = "na"
The note works well here.

Fixed in 2855b7271cc0534780a0c5fbdce51003640134d3.

2024-06-26 17:05 UTC, doamatto commented on products/smspool.toml
> +value = "na"
Fixed in 2855b7271cc0534780a0c5fbdce51003640134d3.

2024-06-26 17:05 UTC, doamatto commented on products/smspool.toml
> +[rubric.noncritical-purposes]
The verdict here was that analytics will continue to be marked as non-critical. Since Cloudflare's analytics are mentioned in Article 2, this should be marked as `no` ; unless you mean the site statistics from having stuff under clouds and not their proper analyitcs offering, then it would stay as `na`. No policy change would be needed, just clarification here.

2024-06-26 17:05 UTC, doamatto commented on products/smspool.toml
> +value = "last-modified"
I meant with the date too, but that *technically* works haha.

2024-06-26 17:07 UTC, doamatto commented on products/smspool.toml
> +  "SMSPool does not store or require any personal data"
I feel quoting and scoring based on Article 6 would still be an ideal solution.

2024-06-26 17:08 UTC, doamatto requested changes
Sorry for the wait and thanks for your patience. Just a few more things (and making sure the tests pass) and then I can get this merged for you (no new comments, just add-ons to the ones above).

2024-09-09 16:13 UTC, doamatto commented on products/smspool.toml
> +[rubric.noncritical-purposes]
Going to assume it's their analytics and not the site statistics. Will welcome the change if it's clarified later on.

2024-09-09 16:15 UTC, doamatto approved these changes

2024-09-09 16:16 UTC, doamatto commented
Waiting for checks to pass, but will merge shortly after. Thanks !

2024-09-09 16:19 UTC, merged

2024-09-09 16:39 UTC, smspool commented
Not a problem, thank you so much.