Add Product: ID.me (online identity verification service)
Politiwatch/privacyspy pull request #187
Opened 2024-08-20 07:07 UTC by opile8

**Type of pull request:** product addition / product edit / bug fix / other...
product addition: ID.me
- included icon and toml, used other products and rubric as guides

**Related issues:** list the related issues here (if applicable)

---

Provide more information about your pull request here. For help, see our contribution guide: http://privacyspy.org/contribute/

2024-08-21 04:33 UTC, doamatto requested changes
A few things that need tweaking. There was also the ID.me Rx section near the bottom that I forget if was included in this. Overall, good start ^_^

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +  "ID.me has been designed to comply with rigorous information security regulations including AICPA SOC 2, ISO 27001, FedRAMP, and multiple NIST 800 guidelines. Multiple ID.me clients have completed
This is the first I'm hearing that USAA FSB started auditing other companies /s

In seriousness, although knowing the U.S. govt and (iirc) the second biggest military-exclusive financial institution trusts them, we could probably omit that portion in the name of brevity (can leave in FIPS, FedRAMP, et al.).

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +  "ID.me previously (until 3/14/2022) allowed login to Facebook using ID.me as the sign-on service (via Facebook Connect). The privacy policy at that time included language about ID.me's collection a
Typo in this section ("but ID.me no no longer"). Retrospective might not be needed, but I'm fine with leaving it in

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +  "We may derive additional information or draw inferences about you based on the information we have collected from you directly, passively, or through third parties."
I think the vagueness of this statement makes `critical-only` hard to justify. From the experiences I've heard others have, it's to check against American credit bureaus for identity verification, but the wording would have to limit it to just that and/or whatever else they collect from.

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +  "It does, however, admit \"[...] that no data transmission or storage can be guaranteed to be 100% secure.\""
Second bit isn't necessary — most services have this line

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +  "We may share your Personal Information with entities necessary to validate your ID.me Account and provide our Services to you. In order to verify your identity and eligibility to receive discounts
"Other trusted and reliable sources of information" is too vague for this to be `yes-specified-critical`. Based on the policy, `yes-unspecified-critical` would be OK

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +  "Verification information. When you verify yourself, either individually or as part of a community, with ID.me you provide us with Personal Information that may include your name, date of birth, so
It makes more sense to quote and score based on section 2 ("How We May Use Your Information and Why").

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +  "ID.me uses this information to become a trusted middleman to verify your affiliation.",
I think explaining the point of ID.me might be out of scope (for lack of better wording)

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +  "We may share information as required with the United States federal government and certain state governments. ID.me does not provide any government with direct and unfettered access to our user's
The section above this ("We may share information as needed in order to comply with legal processes, to protect ourselves, or improve our Services.") would also be a good idea.

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +citations = [
They collect more than what's mentioned here. Basically the whole of section 1

2024-08-21 04:33 UTC, doamatto commented on products/id-me.toml
> +sources = ["https://www.id.me/privacy", "https://id.me/biometric", "https://www.id.me/security", "https://id.me/washington-privacy"]
I don't *think* I saw anything quoted from the Washington state privacy page ? We don't need to quote from there anyways unless it's something that applies to everyone

2024-09-07 15:28 UTC, opile8 commented on products/id-me.toml
> +sources = ["https://www.id.me/privacy", "https://id.me/biometric", "https://www.id.me/security", "https://id.me/washington-privacy"]
Removed. Was used as a placeholder as I explored all of the privacy policies on the site.

2024-09-07 16:07 UTC, opile8 commented on products/id-me.toml
> +  "ID.me has been designed to comply with rigorous information security regulations including AICPA SOC 2, ISO 27001, FedRAMP, and multiple NIST 800 guidelines. Multiple ID.me clients have completed
Removed that sentence. Left other security measures.

2024-09-07 16:11 UTC, opile8 commented on products/id-me.toml
> +  "We may derive additional information or draw inferences about you based on the information we have collected from you directly, passively, or through third parties."
Changed rubric grade to `yes`.

2024-09-07 16:45 UTC, opile8 commented on products/id-me.toml
> +  "It does, however, admit \"[...] that no data transmission or storage can be guaranteed to be 100% secure.\""
Removed second line of "notes"

2024-09-07 20:11 UTC, opile8 commented on products/id-me.toml
> +  "We may share your Personal Information with entities necessary to validate your ID.me Account and provide our Services to you. In order to verify your identity and eligibility to receive discounts
I understand the distinction in the rubric now. Changed as you suggested.

2024-09-07 20:33 UTC, opile8 commented on products/id-me.toml
> +  "Verification information. When you verify yourself, either individually or as part of a community, with ID.me you provide us with Personal Information that may include your name, date of birth, so
cited section 2, included parts about "for marketing purposes"

2024-09-07 20:41 UTC, opile8 commented on products/id-me.toml
> +  "ID.me uses this information to become a trusted middleman to verify your affiliation.",
Updated notes to point to the "non-critical purposes" grade.

2024-09-09 00:31 UTC, opile8 commented on products/id-me.toml
> +  "We may share information as required with the United States federal government and certain state governments. ID.me does not provide any government with direct and unfettered access to our user's
Added citation to law-enforcement for paragraph you referenced.

2024-09-09 00:46 UTC, opile8 commented on products/id-me.toml
> +citations = [
Added section 1

2024-09-09 16:08 UTC, doamatto approved these changes
Looks good now. Thanks !

2024-09-09 16:08 UTC, merged