Added ente
Politiwatch/privacyspy pull request #189
Opened 2024-10-01 17:40 UTC by vkeerthivikram

**Type of pull request:** product addition

**Related issues:** 
#185 

---

Added ente following guidlines mentioned in [https://privacyspy.org/contribute/](https://privacyspy.org/contribute/)

2024-10-01 18:39 UTC, doamatto requested changes
Few changes to make. Could we also find a better icon ? It's very squished.

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +name = "ente"
Should be capitalised.

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = [
Note isn't necessary.

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = [
Note isn't needed

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +citations = ["We collect and store only the bare minimum amount of information necessary to fulfill our role as a service provider."]
See Section 4. The score and citations should be updated.

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = ["The privacy policy provides a clear list of what information is collected and generally explains why, but doesn't give specific reasoning for each data point collected. They emphasize minim
Note isn't needed

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +citations = ["After account termination, we may retain your Data for sixty (60) days, or as warranted by your jurisdiction (\"Retention Period\"), unless an enforcement action is likely under ourTerm
See Section 9 and Section 17. Since only contact is mentioned as a way to delete information, we have to assume (even though it can be done yourself) that it can only be done via e-mail or post.

You can add the automated process as a note.

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = ["The privacy policy states that users can terminate their account, which leads to the permanent deletion of personal data after a retention period. While there's a delay before full deletion
This note isn't needed

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = ["The privacy policy includes a 'Last Updated' date at the beginning, which indicates when the policy was last modified. However, it does not provide a full history of changes or previous ver
Note isn't needed

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = ["The privacy policy states that Ente will only disclose personal information to law enforcement in response to legal processes like court orders or government requests, which aligns with the
Note isn't needed

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +citations = ["Information you Provide: At the time of registration, or through your use of our Services, you will provide us with 1. Your email address; 2. Referral details including referrers and pe
Should also include Section 3d

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = ["The privacy policy provides a detailed and specific list of the types of personal data collected, both provided by the user and automatically collected. This level of detail meets the crite
Note isn't needed

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +citations = ["We collect and store only the bare minimum amount of information necessary to fulfill our role as a service provider."]
Citation isn't relevant

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = ["The privacy policy emphasizes minimal data collection and does not mention any non-critical data collection or usage. There are no opt-out or opt-in options mentioned for non-critical purpo
Simpler to mention that there's no mention in Section 4 of noncritical usage

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = [
Note isn't needed

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +  "Your Files, their metadata and any derived indexes (including but not limited to Biometric Information such as face geometry) are stored end-to-end encrypted."
Citation isn't very relevant

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = [
Current note isn't needed. Note should mention audit : https://ente.io/blog/cryptography-audit/. Given its age, I wouldn't personally say the score should be changed to `yes-independent-audits`.

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +value = "yes"
Should be `somewhat`.

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +citations = ["We do not sell, trade, rent, or otherwise transfer personal information to others, unless we provide you with advance notice. There are times when Personal Information that you have sha
Second citation isn't relevant.

Third citation shouldn't have brackets and "list of providers including"

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = [
Note isn't necessary

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +  "Ente uses the following third-party service providers for the provision of services as detailed under the Terms, as applicable: [list of providers including Apple, Google, Stripe, BitPay, PayPal,
Citation isn't necessary

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +notes = [
Note isn't necessary

2024-10-01 18:39 UTC, doamatto commented on products/ente.toml
> +]
Missing EOF it seems. Leave a blank line at the end of the file

2024-10-01 18:41 UTC, doamatto commented
On a somewhat related note, it looks like a lot of the notes were written by a chatbot or something of the like ? Politiwatch (afaik) doesn't bar contributions of that kind, but it would be interesting to know if that was the case. Apologies for the presumption if that's not the case

2024-10-02 05:24 UTC, vkeerthivikram commented
> On a somewhat related note, it looks like a lot of the notes were written by a chatbot or something of the like ? Politiwatch (afaik) doesn't bar contributions of that kind, but it would be interesting to know if that was the case. Apologies for the presumption if that's not the case

Well, I did rewrite whatever notes I wrote, using an AI to make it look a bit professional. Apologize if that was an issue, I will put my original notes out there instead.

2024-10-02 05:24 UTC, vkeerthivikram commented on products/ente.toml
> +name = "ente"
Done

2024-10-02 05:25 UTC, vkeerthivikram commented on products/ente.toml
> +value = "yes"
Changed it to somewhat and mentioned on how the deletion occurs (using the account settings) in the notes

2024-10-02 05:29 UTC, vkeerthivikram commented
> Few changes to make. Could we also find a better icon ? It's very squished.

Regarding the icon, in the ente press kit, the icon is rectangular shaped, but it fails the tests, so I resized it to square shaped. Is it ok if I submit the rectangular shaped icon?

2024-10-02 16:29 UTC, doamatto approved these changes

2024-10-02 16:31 UTC, merged

2024-10-02 16:31 UTC, doamatto commented
Looks all good now. Thanks ! ^_^