Add Zoho Corporation
Politiwatch/privacyspy pull request #200
Opened 2024-11-06 20:17 UTC by Anon-sec

**Type of pull request:** product addition

**Related issues:** list the related issues here (if applicable)

---
Added privacy statistics for Zoho Corporation. For help, see our contribution guide: http://privacyspy.org/contribute/

2024-11-07 01:14 UTC, doamatto requested changes
Some notes to get started. I'll do a deeper look against Zoho's policy sometime tomorrow, if not by the end of the week.

2024-11-07 01:14 UTC, doamatto commented on icons/zoho.jpg
This needs to be a square icon

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +
Lot of blank space here that shouldn't be.

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +
Needs citation.

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +
Needs citation.

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +
Needs citation.

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +
Needs citation.

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +
Needs citation.

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +  "The policy does not specify a strict timeframe for notifying users about breaches but mentions compliance with laws and regulations, suggesting eventual notification."
We play devil's advocate and assume that although the law says they will, the policy needs to affirm it (even in the case of the GDPR's 72-hour rule). No mention would mean `no` here.

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +  "Zoho mentions that they will notify users of significant changes to the privacy policy either through an email or a prominent notice on the website, giving at least 30 days' advance notice."
Citation is more beneficial than a note.

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +  "We may modify the Privacy Policy at any time, upon notifying you through a service announcement or by sending an email to your primary email address"
It's more beneficial to cite the last updated time rather than a quote better fit for `revision-notify`

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +  "The policy mentions that users can request deletion of their service data (e.g., \"request export or deletion of your service data\") and specifies a clean-up cycle for data removal from active da
This citation doesn't support `yes-contact`. It needs to be more akin to saying "this is how you reach out to us to delete your data" or "this is the self-service deletion process you can use".

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +  "The policy explicitly describes the purposes of data collection, such as using personal data for service delivery, communication, and customer support (e.g., generating invoices, sending marketing
Could you add citations for the reasoning ?

2024-11-07 01:14 UTC, doamatto commented on products/zoho.toml
> +citations = ["Part I: \"Opt out of non-essential electronic communications... by using the ‘unsubscribe’ function.\""]
This seems to be just e-mails — what about the rest of the marketing/advertising and analytics ? If there's no opt-out, this should be changed to `yes`.

2024-11-07 07:37 UTC, Anon-sec commented
> Some notes to get started. I'll do a deeper look against Zoho's policy sometime tomorrow, if not by the end of the week.

Thanks in advance for checking the policy. I'll get these changes done as soon as I'll get a little time.

2024-11-07 07:40 UTC, Anon-sec commented
> > Some notes to get started. I'll do a deeper look against Zoho's policy sometime tomorrow, if not by the end of the week.
> 
> Thanks in advance for checking the policy. I'll get these changes done as soon as I'll get a little time.

If you added this website before me, I'd be grateful.

2024-11-07 19:59 UTC, doamatto commented
Either of us can make an issue to add Zoho — I eventually plan to get to more of the issues relating to adding new policies. You're more than welcome to keep at it, if you want

2024-11-08 13:42 UTC, Anon-sec commented
> Either of us can make an issue to add Zoho — I eventually plan to get to more of the issues relating to adding new policies. You're more than welcome to keep at it, if you want

Thanks I'll keep working on this one then.

2024-11-09 14:52 UTC, Anon-sec commented on products/zoho.toml
> +  "We may modify the Privacy Policy at any time, upon notifying you through a service announcement or by sending an email to your primary email address"
Is there an option for "revision-notify" for this rubric as there is none on the website.

2024-11-09 18:50 UTC, Anon-sec commented on products/zoho.toml
> +
added citation

2024-11-09 18:50 UTC, Anon-sec commented on products/zoho.toml
> +
added citation

2024-11-09 18:50 UTC, Anon-sec commented on products/zoho.toml
> +
added citation

2024-11-09 18:50 UTC, Anon-sec commented on products/zoho.toml
> +  "Zoho mentions that they will notify users of significant changes to the privacy policy either through an email or a prominent notice on the website, giving at least 30 days' advance notice."
Added Citation as well.

2024-11-09 18:51 UTC, Anon-sec commented on products/zoho.toml
> +  "We may modify the Privacy Policy at any time, upon notifying you through a service announcement or by sending an email to your primary email address"
improved on this

2024-11-09 18:52 UTC, Anon-sec commented on products/zoho.toml
> +  "The policy mentions that users can request deletion of their service data (e.g., \"request export or deletion of your service data\") and specifies a clean-up cycle for data removal from active da
added the right information

2024-11-09 18:52 UTC, Anon-sec commented on products/zoho.toml
> +  "The policy explicitly describes the purposes of data collection, such as using personal data for service delivery, communication, and customer support (e.g., generating invoices, sending marketing
added citations

2024-11-09 18:59 UTC, Anon-sec commented on products/zoho.toml
> +citations = ["Part I: \"Opt out of non-essential electronic communications... by using the ‘unsubscribe’ function.\""]
updated citation and modified the value.

2024-11-12 18:40 UTC, doamatto requested changes
Few more things to do — made some of the changes myself, but here's what's left to be taken care of. Thanks for the work so far !

2024-11-12 18:40 UTC, doamatto commented on package-lock.json
I'd rather this and the `package.json` get reverted — I don't have the time right now to try and figure the package changes right this moment. `jest` is slated to be updated in #171 and efforts can be made there if you want

2024-11-12 18:40 UTC, doamatto commented on package.json
> +    "jest": "^27.5.1",
See comment on `package-lock.json`

2024-11-12 18:40 UTC, doamatto commented on products/zoho.toml
> +description = "Zoho Corp is a global software company that offers a suite of cloud-based applications for business productivity, including CRM, project management, and marketing automation tools."
I think I'd leave out the bits after « business productivity » just for brevity

2024-11-12 18:40 UTC, doamatto commented on products/zoho.toml
> +  "Federated Authentication (e.g., Google, LinkedIn): Name, Email, Referrals: Name, Email, Partners & Service Providers: Name, Email, Company, Social Media/Public Sources: Profile info (name, photo,
Should be a note since it's not a quote. Breaking this up could help things a wee bit as well

2024-11-13 14:47 UTC, Anon-sec commented on package-lock.json
reverted them back

2024-11-13 14:48 UTC, Anon-sec commented on products/zoho.toml
> +description = "Zoho Corp is a global software company that offers a suite of cloud-based applications for business productivity, including CRM, project management, and marketing automation tools."
ok

2024-11-13 14:54 UTC, gg-sys1 commented on products/zoho.toml
> +  "Federated Authentication (e.g., Google, LinkedIn): Name, Email, Referrals: Name, Email, Partners & Service Providers: Name, Email, Company, Social Media/Public Sources: Profile info (name, photo,
changed it as per your suggestion.

2024-11-13 14:58 UTC, Anon-sec commented
@doamatto made changes as requested :)

2024-11-25 17:52 UTC, doamatto approved these changes
Sorry for the delay. Things look good so I'll merge when the checks pass.

2024-11-25 18:00 UTC, merged