Add SUMO Scheduler
Politiwatch/privacyspy pull request #201
Opened 2024-11-12 17:19 UTC by maximbelyakov

**Type of pull request:** product addition
**Related issues:** list the related issues here (if applicable)

2024-11-12 18:22 UTC, doamatto requested changes
Here's a few things that need fixing, but a good start

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "Yes, but you may opt-out. If you no longer wish to receive any marketing-related emails from us, you may opt-out via the unsubscribe link included in such emails."
This doesn't seem to be a direct citation and would only cover opt-out from newsletters, not targeted advertising

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "Yes. For detailed information on our data security practices, please refer to our Privacy Policy. https://sumoscheduler.com/privacy-policy/"
Not a citation. Can quote some of the things in the « How do we protect your information ? » section, but the score looks like it would end up being `somewhat` given it's the usual basic precautions most other policies mention

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "Yes, but only critical data (name, phone number, email). We collect and store content that you create, submit, post, upload, transmit, store or display in the process of using SUMO or our websites
This is first, not third party, collection. Should get rescored and a quote to match

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "Yes"
Citation should be of last modified in privacy policy (`These updates will take effect on May 25, 2018.`)

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "Yes, by contacting someone. If your account is managed by a System Administrator, that administrator may have control with regards to how your account information is retained and deleted. However,
Remove « Yes, by contacting someone. » since that's not a quote on the page

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "Yes. For detailed information on our data security practices, please refer to our Privacy Policy. https://sumoscheduler.com/privacy-policy/"
Now that I've seen the security policy a bit farther down, quoting from there and adding a note to check it would be ideal.

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "No, we do not sell, trade, or otherwise transfer to outside parties your personally identifiable information."
Data seems to be shared for advertising, payment processing, and analytics from a quick glance. Score and citation should be updated to reflect — no subprocessors disclosed it seems either, bar Salesforce as the « data hosting provider ».

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +value = "yes"
I'd bid for `mostly` given the vague « For other purposes about which we obtain your consent. » part at the end

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "We collect and store content that you create, submit, post, upload, transmit, store or display in the process of using SUMO or our websites."
Would be ideal to have the full list of collection purposes

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "Yes, but you may opt-out. If you no longer wish to receive any marketing-related emails from us, you may opt-out via the unsubscribe link included in such emails."
Not a direct citation. May be a good idea to add a note mentioning that you're only able to opt-out of e-mails

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "Only when required by a court order or subpoena. We may disclose your information, including your personal data, to a third party if (a) we believe that disclosure is reasonably necessary to compl
First sentence isn't a citation and should be removed

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "No. As per the policy, SUMO reserves the right to amend our Privacy Policy at any time to reflect changes in the law, our data collection and use practices, and the features of our Services. If we
Seems the privacy policy mentions that an e-mail will be sent out — should be updated to reflect. Score is OK

2024-11-12 18:22 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "Yes, but only critical data (name, phone number, email). We collect and store content that you create, submit, post, upload, transmit, store or display in the process of using SUMO or our websites
Should be a citation(s) of the full list of data collected

2024-11-27 09:13 UTC, maximbelyakov commented
@doamatto Could you check please?

2024-11-27 15:15 UTC, doamatto submitted a review, later dismissed
I assume from your GH profile you work here and the quotes might be from an upcoming change. Once it's reflected there, I'll give it another once over to make sure everything's solid in that regard. Until then, I can't merge it since most of the citations don't exist in the policy.

2024-11-27 15:15 UTC, doamatto commented on products/sumo-scheduler.toml
> +citations = [
Can't seem to find these citations. Can move the security policy mention to a note.

2024-11-27 15:15 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "We may receive Personal Information about you from other sources, including through third-party services and organizations to supplement information provided by you."
Citation not in privacy policy

2024-11-27 15:15 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "If your account is managed by a System Administrator, that administrator may have control with regards to how your account information is retained and deleted. However, customers may also contact
Citation not in privacy policy

2024-11-27 15:15 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "We may share your information with third parties that perform services for us or on our behalf, including payment processing, data analysis, email delivery, hosting services, customer service, and
Can't seem to find citation

2024-11-27 15:15 UTC, doamatto commented on products/sumo-scheduler.toml
> +citations = [
Can't find citations

2024-11-27 15:15 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "The personal information that we collect depends on the context of your interactions with us and the Services, the choices you make and the products and features you use. The personal information
Can't find citation

2024-11-27 15:15 UTC, doamatto commented on products/sumo-scheduler.toml
> +  "If we make material changes to this privacy policy, we will notify you by email or by means of a notice on our homepage prior to the change becoming effective."
Can't find citation

2024-12-02 16:31 UTC, maximbelyakov commented on products/sumo-scheduler.toml
> +citations = [
https://sumoscheduler.com/privacy-policy/

I used "How do we protect your information?", the paragraphs: This section discusses the implementation of security measures such as SSL encryption and secure server protocols to safeguard personal information.

Please check

2024-12-02 16:31 UTC, maximbelyakov commented on products/sumo-scheduler.toml
> +  "We may receive Personal Information about you from other sources, including through third-party services and organizations to supplement information provided by you."
Section: "What information do we collect?"
Paragraphs: This section mentions that SUMO may collect information from third-party services to supplement user-provided information.

2024-12-02 16:32 UTC, maximbelyakov commented on products/sumo-scheduler.toml
> +  "If your account is managed by a System Administrator, that administrator may have control with regards to how your account information is retained and deleted. However, customers may also contact
Section: "YOUR CHOICES" and "Personal Data Access"
Paragraphs: These sections describe how users can contact support to request the deletion of their personal data and mention the response time for such requests.

2024-12-02 16:32 UTC, maximbelyakov commented on products/sumo-scheduler.toml
> +  "We may share your information with third parties that perform services for us or on our behalf, including payment processing, data analysis, email delivery, hosting services, customer service, and
Setion: "Do we disclose any information to outside parties?"
Paragraphs: This section explains that information may be shared with third parties for specific services like payment processing and analytics, provided they maintain confidentiality.

2024-12-02 16:32 UTC, maximbelyakov commented on products/sumo-scheduler.toml
> +citations = [
Section: "What do we use your information for?"
Paragraphs: Thhis section outlines the purposes for which data is collected, including improving services, processing transactions, and legal compliance.

2024-12-02 16:32 UTC, maximbelyakov commented on products/sumo-scheduler.toml
> +  "The personal information that we collect depends on the context of your interactions with us and the Services, the choices you make and the products and features you use. The personal information
Section: "What information do we collect?"
Paragraphs: This section lists the types of personal information collected, such as name, contact details, payment information, and usage data.

2024-12-02 16:33 UTC, maximbelyakov commented on products/sumo-scheduler.toml
> +  "If we make material changes to this privacy policy, we will notify you by email or by means of a notice on our homepage prior to the change becoming effective."
Section: "Changes to our Privacy Policy"
Paragraphs: This section describes how users will be notified of material changes to the privacy policy, such as through email or a notice on the homepage.

2024-12-06 11:30 UTC, maximbelyakov commented
@doamatto Hello!

Could you review the changes please?

2024-12-13 13:47 UTC, maximbelyakov commented
@doamatto Do you need any changes more?

2024-12-24 09:10 UTC, maximbelyakov commented
@bcbee @loviuz @milesmcc 

Sorry, can you check it please guys?

2024-12-24 23:09 UTC, doamatto reviewed
Apologies for the delays — I had more pressing matter to attend to recently. This should be everything, but I'll polish it and get this MR merged in a titbit. Thank you for your work

2024-12-24 23:09 UTC, doamatto commented on products/sumo-scheduler.toml
> +citations = [
This is summarising that section, rather than citing it. Summary is fine, but it should be in the notes instead.

2024-12-24 23:09 UTC, doamatto commented on products/sumo-scheduler.toml
> +citations = [
This is summarising that section, rather than citing it. Summary is fine, but it should be in the notes instead.

2024-12-24 23:28 UTC, merged