Create verleihshop.toml
Politiwatch/privacyspy pull request #209
Opened 2024-12-28 03:48 UTC by ErSpieltHD

**Type of pull request:** product addition

**Related issues:** list the related issues here (if applicable)

---

Provide more information about your pull request here. For help, see our contribution guide: http://privacyspy.org/contribute/

2024-12-29 03:15 UTC, doamatto requested changes
Hallo, ich kann ein bisschen Deutsch sprechen, aber ich spreche auch fliessend Englisch und Französisch.

Wenn möglich, sollten die Zitate in deutscher Sprache bleiben (sie können englische Übersetzungen in den Abschnitten « Notizen/notes » hinterlassen, das ist Ok). Ich kann es nach dieser Änderung punkten.

<details open>
<summary>In Englisch / In English</summary>

> If possible, the quotes should be in German (it is OK to leave Englisch translations in the `notes` sections). I can start the review after this

</details>

2024-12-30 00:56 UTC, ErSpieltHD reviewed
Translated it back to German

2024-12-30 01:00 UTC, ErSpieltHD commented
which note section? do you mean the description?

2024-12-30 01:13 UTC, doamatto commented
> Translated it back to German

Danke, ich mache es morgen überprüfen

> which note section? do you mean the description?

```toml
[rubric.behavioral-marketing]
value = ""
citations = []
notes = [] # <-- hier
```

2024-12-30 01:26 UTC, ErSpieltHD commented
Oh okay

2025-01-01 17:20 UTC, doamatto requested changes
Es ist ein guter Anfang. Ich habe einige Kommentare hinterlassen. Bitte stellen Sie sicher, dass die CI/CD-Prüfungen (siehe [hier](https://github.com/Politiwatch/privacyspy/pull/209/checks)) in Ordnung sind.

Vielen Dank für die bisherige Arbei. Ich hoffe dass das neue Jahr gut für euch ist

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "Verleihshop.de verwendet Cookies und ähnliche Technologien, um das Nutzerverhalten zu analysieren und personalisierte Werbung bereitzustellen. Nutzer können der Verwendung von Cookies widerspreche
Das ist kein Zitat aus dem Datenschutz. Ich kann nicht finden, dass die opt-out erlaubt ist.

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "Verleihshop.de setzt technische und organisatorische Sicherheitsmaßnahmen ein, um personenbezogene Daten vor Verlust, Missbrauch und unbefugtem Zugriff zu schützen. Details zu den spezifischen Maß
Dies ist kein Zitat. Es wird nicht erwähnt, wie die Daten gesichert werden - das sollten als `no` bewertet werden

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "Verleihshop.de arbeitet mit Drittanbietern zusammen, um bestimmte Funktionen bereitzustellen und Dienstleistungen zu erbringen. Dabei können personenbezogene Daten an diese Drittanbieter weitergeg
Das ist kein Zitat. Die gesammelten Daten stammen von PayPal, Amazon Pay und Sofort, wobei Sofort ist für eine Kreditlinie verwendet wird — `critical-only` scheint mir angemessen

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "The date of the last update is indicated at the end of the privacy policy. (Das Datum der letzten Aktualisierung ist am Ende der Datenschutzerklärung angegeben.)"
Ich kann nicht finden das

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "Nutzer haben das Recht, die Löschung ihrer personenbezogenen Daten zu verlangen. Anfragen zur Datenlöschung können über die in der Datenschutzerklärung angegebenen Kontaktinformationen gestellt we
Das ist kein Zitat — aber unten ist OK :

> Sie haben jederzeit das Recht unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Sie haben außerdem ein Recht, die Berichtigung, Sperrung oder Löschung dieser Daten zu verlangen. Hierzu sowie zu weiteren Fragen zum Thema Datenschutz können Sie sich jederzeit unter der im Impressum angegebenen Adresse an uns wenden.
> [...]
> Jakob GmbH
> Herr Dieter Jakob
> Bindlacher Str. 8
> 95448 Bayreuth
> 
> Telefon: 0921 7969 15
> E-Mail: datenschutz@jakob.de

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +value = "yes-unspecified"
Es scheint klar zu sein, mit wem die Daten geteilt werden (Facebook, Twitter, Google+, Instagram, Google AdWords, Google Conversion Tracking, Trusted Shops, Trustami, YouTube, Google Web Fonts, PayPal Europe, Amazon Services Europe, Sofort) — siehe Abschnitte 5, 6, 8, 9

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "Personenbezogene Daten können an Dritte weitergegeben werden, wenn dies zur Vertragserfüllung erforderlich ist oder eine gesetzliche Verpflichtung besteht. Details zu den spezifischen Empfängern w
Das ist kein Zitat

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +[rubric.data-collection-reasoning]
Ist es möglich einige Zitate hinzuzufügen ?

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "Nutzer können der Verwendung ihrer Daten für bestimmte nicht kritische Zwecke widersprechen, jedoch nicht für alle."
Kein Zitat

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "Verleihshop.de kann personenbezogene Daten offenlegen, wenn dies gesetzlich vorgeschrieben ist oder zur Wahrung berechtigter Interessen erforderlich ist."
Kein Zitat. Ich kann keine Erwähnung von Datenaustausch mit LEA/Untersuchungsbehörde finden

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "The privacy policy lists the data collected in general, but some categories of data are not specifically mentioned. (Die Datenschutzerklärung listet die gesammelten Daten allgemein auf, jedoch wer
Wie was? Auch Zitat(en) können hinzugefügt werden, wenn es möglich ist ?

2025-01-01 17:20 UTC, doamatto commented on products/verleihshop.toml
> +  "Verleihshop.de behält sich das Recht vor, die Datenschutzerklärung zu ändern. Nutzer werden über wesentliche Änderungen informiert."
Kein Zitat

2025-02-12 22:33 UTC, closed without merging