Product addition: Opera
Politiwatch/privacyspy pull request #39
Opened 2020-09-30 20:56 UTC by Quoot

**Type of pull request:** product addition

---

This is a pull request to add Opera as a product. Only note would be that I couldn't figure out how to run it locally to test if everything at least _functioned_, as I am rather new at GitHub, but I double checked all of the additions and everything looks like it should be good format-wise.

2020-09-30 21:53 UTC, milesmcc requested changes
Thanks, Quintin! This looks great. I just left a few very small comments, then we'll be all set to merge!

2020-09-30 21:53 UTC, milesmcc commented on products/opera.toml
> +  "While they do not collect data from third parties, they often use thrid parties to interact with your data, such as personalized ads and news.\r\n\r\nA full list of third parties they use for this
I think this sentence needs a comma at the end.

2020-09-30 21:53 UTC, milesmcc commented on products/opera.toml
> +  "They only mention why advertisement data is collected."
Is it possible to add a citation here?

2020-10-01 19:48 UTC, Quoot commented on products/opera.toml
> +  "While they do not collect data from third parties, they often use thrid parties to interact with your data, such as personalized ads and news.\r\n\r\nA full list of third parties they use for this
Done.

2020-10-01 19:51 UTC, Quoot commented on products/opera.toml
> +  "They only mention why advertisement data is collected."
I added a citation here but I wasn't too sure how to format it well. Right now I have this:

"We collect this data pursuant to our legitimate business interests. As noted in our End User License Agreements and Terms of Service, our applications are ad-supported. Collecting this information helps us offset the costs of our business and helps provide a more personalized experience for the user."

Does my note make it clear enough that they're talking about ad data?

2020-10-01 20:22 UTC, milesmcc approved these changes

2020-10-01 20:22 UTC, merged

2020-10-01 20:22 UTC, milesmcc commented
Looks good to me! Thanks for writing this out.