Product addition(Ecosia)
Politiwatch/privacyspy pull request #42
Opened 2020-11-10 00:28 UTC by SIVAH-AKASH

**Type of pull request:** product addition / product edit / bug fix / other...

**Related issues:** list the related issues here (if applicable)

---

Provide more information about your pull request here. For help, see our contribution guide: http://privacyspy.org/contribute/

2020-11-10 00:48 UTC, SIVAH-AKASH reviewed
I am new to GitHub so I hope I got everything right this time around. :)

2020-11-10 22:54 UTC, ibarakaiev requested changes
Hi! Thanks for submitting this. I noticed that this submission is a follow-up on your old PR which you closed — in fact, you can update changes in existing pull requests so it's easier to maintain. Before I can add the product to the database, we'd need to implement a few changes. Please go over my comments and resubmit; let me know if you have questions!

2020-11-10 22:54 UTC, ibarakaiev commented on products/ecosia.toml
> +  "\"Temporary storage of IP address, Date and time of enquiry, Difference between time zone and Greenwich Mean Time (GMT), Content of the request (specific webpage), Access status or HTTP status cod
Please remove `\"` from the citation.

2021-06-15 21:25 UTC, closed without merging

2021-06-15 21:25 UTC, milesmcc commented
Feel free to reopen if you want to take this further! I've closed it because it has been open for so long—not because we don't want it. (We do.)