Fixed several products
Politiwatch/privacyspy pull request #44
Opened 2020-12-10 03:04 UTC by doamatto

**Type of pull request:** Product edit(s)

---

**Changes**
- Added self as contributor for products mentioned below
- Fixed behavioural marketing citations and score for 2ndLine

2020-12-10 19:20 UTC, doamatto commented
I could be wrong, but the CI seems bugged. It's saying there isn't a Shazam icon, but there is a vector  [here](https://github.com/doamatto/privacyspy/blob/patch-1/icons/shazam.svg) and removed the past 2 errors of it.

2020-12-11 01:15 UTC, milesmcc commented
It’s not bugged. The slug for Shazam must exactly match the name of the icon. Change Shazam’s slug to be lowercase to fix the issue (slugs should always be lowercase; we should add a test for this).

2020-12-11 01:16 UTC, milesmcc commented
Thanks for these fixes!

2020-12-11 04:34 UTC, doamatto commented
> It’s not bugged. The slug for Shazam must exactly match the name of the icon. Change Shazam’s slug to be lowercase to fix the issue (slugs should always be lowercase; we should add a test for this).
@milesmcc It does match the slug; it's apparently because it isn't mostly square. I must have missed it in some documentation somewhere. I fixed the upload; should be ready for merge now.

2020-12-11 17:16 UTC, milesmcc commented
Ah good catch. I'm so used to people mixing up the capitalization that I missed the 'mostly square' part!

2020-12-11 18:40 UTC, ibarakaiev requested changes
Left two comments on BBC; everything else looks good.

2020-12-11 18:40 UTC, ibarakaiev commented on products/bbc.toml
> +value = "na"
I don't really understand why it makes sense to have `na` here. Can you clarify? Naturally, if a user doesn't provide an email then they shouldn't be notified, but it seems like there is an option to create an account so `na` is not applicable.

2020-12-11 18:40 UTC, ibarakaiev commented on products/bbc.toml
> +notes = "There is no mention of collecting data from third parties."
Good catch that they don't collect data from third parties. However, `notes` should be an array.

2020-12-11 20:40 UTC, doamatto commented on products/bbc.toml
> +value = "na"
In that case, I'll revert these changes.

2020-12-11 20:42 UTC, doamatto commented on products/bbc.toml
> +notes = "There is no mention of collecting data from third parties."
My bad; fixed

2020-12-11 20:42 UTC, doamatto commented
> Left two comments on BBC; everything else looks good.

Alright; I've fixed those issues and re-requested a review.

2020-12-11 20:45 UTC, ibarakaiev commented
Looks good, thanks :)

2020-12-11 20:46 UTC, merged