Product addition: brave, signal, telegram
Politiwatch/privacyspy pull request #53
Opened 2021-01-10 16:13 UTC by erotavlasme

**Type of pull request:** product addition
**Related issues:** No

---

Adding new products: brave, signal, telegram. The first one was a little bit more complicated. The other two are quite straightforward.

2021-01-10 17:29 UTC, milesmcc commented
Hi! Thanks for submitting this pull request. While the original products seem to pass all automated checks (Brave, Signal, and Telegram), the more recent ones don't (Mozilla and Wire). I recommend that you submit those additional products in a separate pull request so that we can move forward with this one. Let me know how you'd like to proceed. Thanks again!

2021-01-11 06:37 UTC, erotavlasme commented
Hi, I'm still working on Mozilla, WhatsApp, and Wire and I will submit them later. Thank you

2021-01-13 17:45 UTC, erotavlasme commented
Hi,
I completed the review for brave, mozilla, signal, telegram and wire. I'm going to start the review for whatsapp. Since it has two quite different privacy policies for Europe (thank to GDPR) and rest of the world. Which one should I analyze?
Thank you

2021-01-13 18:05 UTC, ibarakaiev commented
Hi, thanks so much for doing this! While @milesmcc is getting back to you on this pull request, please create separate pull requests for different products in the future. That simplifies our review as each product gets automatically assigned either to me or Miles. Currently, Miles gets more work that could be split. You don't have to do that now though.

2021-01-14 21:43 UTC, milesmcc requested changes
Thanks for these submissions! We really appreciate it. I noticed several issues in these assessments, so please go through and fix them and then we'll be ready to check again!

Mostly, the issues had to do with correspondence between citations and value selections, as well as some formatting things.

Thanks for contributing! I'm really looking forward to getting these merged.

2021-01-14 21:43 UTC, milesmcc commented on products/whatsapp.toml
> +[rubric.behavioral-marketing]
All of these need citations or notes.

2021-01-14 21:43 UTC, milesmcc commented on products/brave.toml
> +[rubric.security]
Can you format the TOML files so that they parse correctly on GitHub? Thanks! (Notice how the text is red.)

2021-01-14 21:43 UTC, milesmcc commented on products/mozilla.toml
> +[rubric.data-collection-reasoning]
Something went wrong with the formatting here; could you reformat so that GitHub parses it correctly?

2021-01-14 21:43 UTC, milesmcc commented on products/signal.toml
> +name = "Signal"
Great!

2021-01-14 21:43 UTC, milesmcc commented on products/telegram.toml
> +description = "Telegram is a messaging app with a focus on speed and security, it’s super-fast, simple and free."
Could you rework the description to be more neutral? How about "Telegram is a free instant messaging tool."

2021-01-14 21:43 UTC, milesmcc commented on products/telegram.toml
> +[rubric.third-party-collection]
Could you reformat the TOML so that GitHub correctly highlights the syntax here?

2021-01-14 21:43 UTC, milesmcc commented on products/telegram.toml
> +    "Telegram does not collect any data from third parties."]
I just checked, and this sentence is not ever mentioned in the Telegram privacy policy. It should not be a citation; it should be a note instead. Please go through and very that all your citations are pulled verbatim from the policies — thanks!

2021-01-14 21:43 UTC, milesmcc commented on products/whatsapp.toml
> +description = "WhatsApp is freeware, cross-platform messaging and Voice over IP (VoIP) service owned by Facebook, Inc."
Could we change the description to "WhatsApp is a free cross-platform messaging app owned by Facebook."? Just a bit shorter.

2021-01-14 21:43 UTC, milesmcc commented on products/wire.toml
> +  "\"All conversation content is encrypted with strong encryption on the sender's device and is only decrypted on the recipient's device (also known as end-to-end encryption). Wire doesn't hold the d
Nothing in this citation suggests they have independent audits. Are you sure this is the appropriate value?

2021-01-14 21:43 UTC, milesmcc commented on products/wire.toml
> +[rubric.data-breaches]
Could you fix the formatting so that GitHub highlights the syntax here correctly?

2021-01-15 14:29 UTC, erotavlasme commented on products/whatsapp.toml
> +[rubric.behavioral-marketing]
Right, I'm working on it.

2021-01-15 14:34 UTC, erotavlasme commented on products/telegram.toml
> +description = "Telegram is a messaging app with a focus on speed and security, it’s super-fast, simple and free."
Ok, I took it from [telegram faq](https://telegram.org/faq#q-what-is-telegram-what-do-i-do-here). Telegram is a free, cross-platform, cloud-based instant messaging service. Ok?

2021-01-15 14:36 UTC, erotavlasme commented on products/whatsapp.toml
> +description = "WhatsApp is freeware, cross-platform messaging and Voice over IP (VoIP) service owned by Facebook, Inc."
Ok

2021-01-15 14:38 UTC, erotavlasme commented on products/wire.toml
> +  "\"All conversation content is encrypted with strong encryption on the sender's device and is only decrypted on the recipient's device (also known as end-to-end encryption). Wire doesn't hold the d
Yes, you will find it on [Find out more](https://wire.com/en/security/)->[Independently audited](https://wire.com/en/security/#audits).

2021-01-15 14:46 UTC, erotavlasme commented on products/telegram.toml
> +    "Telegram does not collect any data from third parties."]
I followed the same rule for all the services: double quotes when is copied from their privacy policy. I will change from citations to notes, this is a mistake. This apply to brave, mozilla, signal and wire too.

2021-01-15 15:36 UTC, erotavlasme commented on products/brave.toml
> +[rubric.security]
Fixed

2021-01-15 15:36 UTC, erotavlasme commented on products/mozilla.toml
> +[rubric.data-collection-reasoning]
Fixed

2021-01-15 15:36 UTC, erotavlasme commented on products/telegram.toml
> +[rubric.third-party-collection]
Fixed

2021-01-15 15:36 UTC, erotavlasme commented on products/wire.toml
> +[rubric.data-breaches]
Fixed

2021-01-18 17:53 UTC, erotavlasme commented
Hi,
I just completed whatsapp, I used the current [global privacy policy](https://www.whatsapp.com/legal/privacy-policy), not the [new criticized one](https://www.whatsapp.com/legal/updates/privacy-policy).

2021-03-01 15:18 UTC, closed without merging