Product addition: ProtonMail
Politiwatch/privacyspy pull request #82
Opened 2021-05-27 16:24 UTC by Deivedux

**Type of pull request:** product addition

**Related issues:** no issues

---

This is my first contribution to PrivacySpy. As such, I wasted around 5 hours fact checking to make sure the information is as accurate and unbiased as possible.

2021-05-27 18:09 UTC, milesmcc commented
Hey! Thanks so much for this contribution. It looks great. One small thing: would you be able to upload another icon for ProtonMail? Right now, the icon is rectangular and we need a more square icon. Thanks!

Excited to merge.

2021-05-27 18:16 UTC, Deivedux commented
I downloaded that icon from the service's official branding page, and didn't bother looking into its aspect ratio. Will update in a bit.

2021-05-27 18:30 UTC, milesmcc approved these changes

2021-05-27 18:31 UTC, milesmcc commented
Generally LGTM. Happy to let this override the copy in #12. Going to leave this open for a day or so in order for others to comment and then merge. Feel free to follow up with me if I don't merge by Saturday.

2021-05-27 23:02 UTC, doamatto requested changes
Agreeing with @milesmcc; looks pretty bang on to me. Only could find two things that would need changing.

2021-05-27 23:02 UTC, doamatto commented on products/protonmail.toml
> +notes = ["ProtonMail has once received, what seems to be, an \"organized\" independent audit, though these are not mentioned in the policy as their official security measure."]
Can include a link to their [security page](https://protonmail.com/security-details)

2021-05-27 23:19 UTC, Deivedux commented on products/protonmail.toml
> +hostnames = [ "protonmail.com", "protonmail.ch" ]
Actually, good call. I always thought that the domain was only used as a short address for emails, never knew that it's actually its own website.

2021-05-27 23:22 UTC, Deivedux commented on products/protonmail.toml
> +notes = ["ProtonMail has once received, what seems to be, an \"organized\" independent audit, though these are not mentioned in the policy as their official security measure."]
Well, the security policy doesn't seem to mention anything about audits either, but sure.

Btw, do you think the note that I added last minute is unnecessary? Now that the time has passed a little I'm now starting to realize that it's just telling a random fact rather than comment on the policy.

2021-05-28 05:12 UTC, doamatto commented on products/protonmail.toml
> +notes = ["ProtonMail has once received, what seems to be, an \"organized\" independent audit, though these are not mentioned in the policy as their official security measure."]
I don't think it's enough to change the score for it to (independent) audits, but I reckon it would make sense to keep the note. Try to rewrite it to sound more Wikipedia-esque though. Like: `Protonmail has one received an independent audit [...]`. No need for the fluff like "what seems to be" since there's really no in between in this case.

2021-05-28 05:13 UTC, doamatto commented
@Deivedux you can re-request my review once you make the revisions and I'll (almost definetely) approve them.

2021-05-28 16:11 UTC, Deivedux commented
I'm starting to wonder if it would be a good idea to change the data breach from `no` to `na` for ProtonMail... They do, in fact, not have a data breach protocol, but considering their data collection practices makes me want to give them the benefit of the doubt.

Really, they only collect critically important data necessary to provide the service (only emails from what I understand), and most of it is encrypted anyway (the email data, though not the metadata).

Please share your thoughts on this before merging!

2021-05-28 16:16 UTC, milesmcc commented
> I'm starting to wonder if it would be a good idea to change the data breach from `no` to `na` for ProtonMail... They do, in fact, not have a data breach protocol, but considering their data collection practices makes me want to give them the benefit of the doubt.
> 
> Really, they only collect critically important data necessary to provide the service (only emails from what I understand), and most of it is encrypted anyway (the email data, though not the metadata).
> 
> Please share your thoughts on this before merging!

I disagree. As far as I understand, PGP only encrypts the body of the email. They still store the sender, recipient list, and subject in plaintext. A data breach could be catastrophic for their users.

See https://protonmail.com/support/knowledge-base/does-protonmail-encrypt-email-subjects/

2021-05-28 16:25 UTC, doamatto approved these changes

2021-05-28 16:32 UTC, doamatto commented
> I'm starting to wonder if it would be a good idea to change the data breach from `no` to `na` for ProtonMail... They do, in fact, not have a data breach protocol, but considering their data collection practices makes me want to give them the benefit of the doubt.
> 
> Really, they only collect critically important data necessary to provide the service (only emails from what I understand), and most of it is encrypted anyway (the email data, though not the metadata).
> 
> Please share your thoughts on this before merging!

Same side as @milesmcc; `no` would be the right answer. Found one other thing just now; making a comment right now.

2021-05-28 16:36 UTC, doamatto commented on products/protonmail.toml
> +notes = ["ProtonMail does not collect any non-critical personal data."]
they do collect some non-essential on their website (not 100% if it's also in the mail client): they self-host a [Matomo](https://matomo.org) instance. In their mobile app, however, they use things such as:
- Fabric.io statistics and crash reporting
- Play Store statistics
- App Store statistics
- Sentry (self-hosted) crash reporting

There is no mention in the privacy policy as to how to opt-out of this. Arguably, it is essential to have crash reporting and telemetry to make sure your app is functioning well outside of reports, but you can also argue the opposite based on the data gathered by Fabric or Sentry. I'll let you decide which is the better route.

<details>
<summary>Quote</summary>
When you use our native applications, we (or the mobile app platform providers) may collect certain information in addition to the information mentioned elsewhere in this Policy. We may use mobile analytics software (such as fabric.io app statistics and crash reporting, Play Store app statistics, App Store app statistics, or self-hosted Sentry crash reporting) to send crash information to our developers so that we can fix bugs rapidly. 
</details>

2021-05-28 16:42 UTC, Deivedux commented
Alright, thank you for your insights. I'm all done with this PR then.

2021-05-28 21:41 UTC, Deivedux commented on products/protonmail.toml
> +notes = ["ProtonMail does not collect any non-critical personal data."]
I totally missed that, will take a look at it now.

2021-05-28 22:07 UTC, Deivedux commented on products/protonmail.toml
> +notes = ["ProtonMail does not collect any non-critical personal data."]
Gosh, I'm not really sure on that one... 

I could argue for self-hosting Matomo and Sentry, and relying on the app store analytics data since that's the type of thing that "just exists" and you can't just tell the app store to not do that. But defending those same app stores that all data they collect is anonymous even to the store operators themselves is a bit misleading. Sure, the analytics data tracked by the app store may be anonymous to ProtonMail, but is definitely not to the app store operators.

With that in mind, I think it's safe to say that ProtonMail themselves are not gathering any personal information from using these analytical trackers, though the platforms that we use their products are, which is outside their control.

Any other thoughts on this?

2021-05-29 05:47 UTC, doamatto commented on products/protonmail.toml
> +notes = ["ProtonMail does not collect any non-critical personal data."]
Like I said, you could argue either way. Personally, I'm leaning towards including it since, even if you aren't using the data, you are still collecting it.

2021-05-29 12:41 UTC, Deivedux commented on products/protonmail.toml
> +notes = ["ProtonMail does not collect any non-critical personal data."]
I have decided to change the value. In reality, it's not a question whether they collect the data, but whether they give the users the control whether their data is being collected.

2021-05-30 04:25 UTC, merged