Product addition: Signal
Politiwatch/privacyspy pull request #83
Opened 2021-05-30 14:32 UTC by Deivedux

**Type of pull request:** product addition

**Related issues:** no issues

2021-05-30 18:55 UTC, doamatto reviewed
Don't have a chance to check yet, but Signal is already on PrivacySpy ([see here](https://github.com/Politiwatch/privacyspy/blob/master/products/signal.toml))

2021-05-30 19:05 UTC, Deivedux commented
Oh wait... It wasn't on a site, how does that happen then?

2021-05-30 20:46 UTC, ibarakaiev commented
@Deivedux sorry, that's because we had a year-long PR with legacy import from our old version which we merged just today. I'll still take a look at this PR shortly and add you as a contributor to Signal.

2021-05-30 21:28 UTC, Deivedux commented
Thank you for notifying me of this. I'll use the selected version of Signal as a reference to learn how to more accurately read the policies.

2021-05-31 00:12 UTC, milesmcc commented
> Thank you for notifying me of this. I'll use the selected version of Signal as a reference to learn how to more accurately read the policies.

To be honest, take it with a grain of salt. There's room for error in these policies. If you see something that looks off or different from your assessment, it's possible that the error is in the other policy—not yours.

2021-06-12 18:39 UTC, doamatto commented
We may want to close #66 in favour of this PR; review of this PR coming in a hot minute.

2021-06-12 18:43 UTC, doamatto requested changes
Sorry for the long wait for a review. Here's my thoughts.

2021-06-12 18:43 UTC, doamatto commented on products/signal.toml
> +sources = ["https://signal.org/legal/"]
May be a good idea to go straight to the proper section (`https://signal.org/legal/#privacy-policy`)

2021-06-12 18:43 UTC, doamatto commented on products/signal.toml
> +notes = ["No history or policy's modification date is made available."]
Last modified at bottom of page: `Effective as of May 25, 2018 Updated May 25, 2018`. If the site's source is on GitHub, you'd be able to also get a history from there.

2021-06-12 18:43 UTC, doamatto commented on products/signal.toml
> +citations = ["Other instances where Signal may need to share your data\r\n- To meet any applicable law, regulation, legal process or enforceable governmental request."]
Could be reduced to `reasonable` with `To protect against harm to the rights, property, or safety of Signal, our users, or the public as required or permitted by law.`

2021-06-12 18:44 UTC, doamatto reviewed
Also, you may just want to use the image already on PrivacySpy; whatever suits your fancy though.

2021-06-13 17:42 UTC, milesmcc commented on products/signal.toml
> +sources = ["https://signal.org/legal/"]
Also, we typically wouldn't capitalize "End-to-End Encryption" — it's not a proper noun.

2021-06-13 17:42 UTC, milesmcc commented
Everything @doamatto says is right. Fix that up and then we should be good to go! Thanks for this contribution.

2023-08-14 09:43 UTC, closed without merging