Product addition: Blizzard Entertainment
Politiwatch/privacyspy pull request #84
Opened 2021-06-01 13:54 UTC by Deivedux

**Type of pull request:** product addition

**Related issues:** no issues

---

A few things worth mentioning.

- The list of hostnames may not be complete. These are all what I could find during the time that I subjectively gave myself, and I was kind of out of patience at the end.
- There are 2 different policies, called **Privacy Policy** and **Online Privacy Policy**. I chose the latter one because that's the first result that appeared in search engines, and it's the one that Blizzard themselves makes the most accessible from their websites' footer.

2021-06-01 15:17 UTC, doamatto reviewed
I'll look into it more once I'm back at my flat or have a chance while on campus.

2021-06-01 15:17 UTC, doamatto commented on products/blizzard-entertainment.toml
> +hostnames = [
Consider playoverwatch.com, overwatchleague.com and overwatchcontenders.com. On campus right now so I cant check if they are under the same policy or not

2021-06-01 15:33 UTC, Deivedux commented on products/blizzard-entertainment.toml
> +hostnames = [
The first one is already in the list. And yes, they are all under the same policy, since they all have the same footer by Blizzard that leads to the same policy page.

2021-06-01 17:16 UTC, doamatto reviewed
Some more sites that would go under this product

2021-06-01 17:16 UTC, doamatto commented on products/blizzard-entertainment.toml
> +  "overwatchcontenders.com"
Add:
```
- communitytournaments.blizzardesports.com
- blizzard.gamespress.com
- blizzcon.com
```

2021-06-01 17:26 UTC, Deivedux commented on products/blizzard-entertainment.toml
> +  "overwatchcontenders.com"
Is it fine if subdomains are included as well?

2021-06-02 21:39 UTC, Deivedux commented on products/blizzard-entertainment.toml
> +  "overwatchcontenders.com"
I decided not to add the second one, as it may conflict with their policy in the future.

2021-06-02 23:20 UTC, doamatto commented on products/blizzard-entertainment.toml
> +  "overwatchcontenders.com"
> Is it fine if subdomains are included as well?
That would be best asked to @milesmcc or @ibarakaiev, but my assumption is that it's whatever the hostname is + a wildcard (*.google.com would be under Google, but news.google.com could have a seperate entry, for instance)

2021-06-12 18:31 UTC, doamatto requested changes
Sorry for the long wait for a proper review. Here's my thoughts.

2021-06-12 18:31 UTC, doamatto commented on products/blizzard-entertainment.toml
> +name = "Blizzard Entertainment"
`Blizzard Entertainment (US)` would be more accurate, as the policies vary between regions.

2021-06-12 18:31 UTC, doamatto commented on products/blizzard-entertainment.toml
> +  "You may also submit a verifiable request for us to delete either: (1) your marketing information; or (2) your Battle.net account and your marketing information.",
This should be automated: `The deletion of a Battle.net account is permanent and cannot be reversed; also, all games, assets and history will also be permanently deleted.`

2021-06-12 18:31 UTC, doamatto commented on products/blizzard-entertainment.toml
> +notes = ["The policy's history is not made available."]
Should be last modified. Date at bottom of policy: `This Privacy Policy was last updated on October 22, 2020`

2021-06-12 18:31 UTC, doamatto commented on products/blizzard-entertainment.toml
> +citations = ["This Privacy Policy may change from time to time, so please check back periodically to ensure that you are aware of any changes. If we make a material change to this Privacy Policy, we
Material changes would qualify as revision notifications, and should bring this score up

2021-06-13 17:45 UTC, milesmcc commented
@doamatto is right! Incorporate those suggestions and we should be good to go.

2021-06-15 11:51 UTC, Deivedux commented on products/blizzard-entertainment.toml
> +  "You may also submit a verifiable request for us to delete either: (1) your marketing information; or (2) your Battle.net account and your marketing information.",
Sure, the account deletion is permanent, but they do mention that they may retain some information for reasons like `(d) comply with law enforcement requests pursuant to lawful process, (e) for scientific or historical research`, no? This to me suggests that they will still have enough personal information to give away to law enforcement even after the account is deleted.

2021-06-15 11:53 UTC, Deivedux commented on products/blizzard-entertainment.toml
> +citations = ["This Privacy Policy may change from time to time, so please check back periodically to ensure that you are aware of any changes. If we make a material change to this Privacy Policy, we
I honestly do not know why I put `no` here...

2021-06-15 17:57 UTC, doamatto commented on products/blizzard-entertainment.toml
> +citations = ["This Privacy Policy may change from time to time, so please check back periodically to ensure that you are aware of any changes. If we make a material change to this Privacy Policy, we
Haha all good bruv

2021-06-15 17:59 UTC, doamatto commented on products/blizzard-entertainment.toml
> +  "You may also submit a verifiable request for us to delete either: (1) your marketing information; or (2) your Battle.net account and your marketing information.",
The first bit is technically unavoidable and something I think many ignore because some information does have to be. Prime example is an order history for tax audits. May be a good idea to get a second opinion from @milesmcc or @ibarakaiev though.

2021-06-15 18:02 UTC, doamatto commented on products/blizzard-entertainment.toml
> +  "overwatchcontenders.com"
Checked the extension source and [saw that (in theory) the subomdina will be fine](https://github.com/Politiwatch/PrivacySpy-Extension/blob/be573d5e453b96c9ad5012b3c5e427097a542b54/src/background.js#L105). If you want to be certain, I can load up a custom version of the extension and this PR locally and double-check that it doesn't have any issues (you can if you want as well)

2021-06-18 13:45 UTC, Deivedux reviewed
Need to look into these before merging.

2021-06-18 13:45 UTC, Deivedux commented on products/blizzard-entertainment.toml
> +  "We may retain personal information to: (a) protect our business, systems, and users from fraudulent activity, (b) to address technical issues that impair existing functionality, (c) necessary for
This may be conflicting information with the value.

2021-06-18 13:45 UTC, Deivedux commented on products/blizzard-entertainment.toml
> +notes = ["The users are not independantly notified of the policy changes unless they visit the website."]
This'd need further confirmation, which is outside my scope.

2021-06-18 15:13 UTC, doamatto commented on products/blizzard-entertainment.toml
> +  "We may retain personal information to: (a) protect our business, systems, and users from fraudulent activity, (b) to address technical issues that impair existing functionality, (c) necessary for
We are working on a new option for data deletion intervals (see #97) that would help with this

2021-06-18 15:19 UTC, doamatto commented on products/blizzard-entertainment.toml
> +notes = ["The users are not independantly notified of the policy changes unless they visit the website."]
I can see how it's arguable otherwise, but I think this note sums it up. Because, technically, there are technically revision notifications.

2021-06-18 15:19 UTC, doamatto commented
Looks pretty solid to me; some things can be changed after #97 is finished, but apart from that it looks basically bang-on to me

2021-06-18 16:50 UTC, merged